development.ts, dist/development.d.ts, dist/testing/execution.d.ts, dist/testing/execution.js, dist/testing/execution_helper.d.ts, dist/testing/execution_helper.js, dist/testing/execution_helper_bundle.js, test/execution_test.ts, testing/execution.ts, testing/execution_helper.ts, testing/validation.ts
https://staging.coda.io/d/Packs-IA-go-packs_d36WK4zgrYx/Bugs-Feature-requests_suyN0#Open-Bugs_tu6FU/r26
This PR fixes the bug and further narrows the gap between the lambda execution and the sdk execution. Instead of having IVM thunk to iterate though all the pages, now it's the sdk iterating the pages and thunk only executes a single request. 
Now if a pack author uses a global variable to store page number, it's going to fail in the CLI execution (with VM).
Testing:
```
➜  packs-sdk git:(hg-sync-cli) node_modules/.bin/ts-node cli/coda.ts execute test/packs/fake.ts Students Smith  --vm
[
{ Name: 'Alice' },
{ Name: 'Bob' },
{ Name: 'Chris' },
{ Name: 'Diana' }
]
➜  packs-sdk git:(hg-sync-cli) node_modules/.bin/ts-node cli/coda.ts execute test/packs/fake.ts Students Smith      
[
{ Name: …
```
=> create separate ivm context for each sync formula execution

development.ts, dist/development.d.ts, dist/development.js, dist/testing/execution.d.ts, dist/testing/execution.js, test/execution_test.ts, testing/execution.ts
I'm trying to bump the SDK in the packs repo and the change in functionality of executeSyncFormulaFromPackDef is breaking a bunch of tests there, that rely on the fact that it runs a sync to completion. It will also break packs-examples, and possibly customers who bothered to write unittests (don't know if there are any).
It is fair that it's probably more useful to test a single iteration and be able to inspect the returned continuation, and sidestep the fact that we don't run the loops in isolation in the context of a unittest or integration test yet. But I'd rather not have this be a breaking change and have to fix all those tests and tell users to do the same, we can try to have this use the VM too when it's ready.
PTAL @huayang-codaio @alan-codaio @coda/packs
=> Return executeSyncFormulaFromPackDef to its original behavior of running the sync in a loop to preserve backwards compatibility.

cli/create.ts, cli/errors.ts, cli/register.ts, cli/release.ts, cli/upload.ts, dist/cli/create.js, dist/cli/errors.d.ts, dist/cli/errors.js, dist/cli/register.js, dist/cli/release.js, dist/cli/upload.js
Prints out an extra line at the end:
```
Unexpected error during Pack upload: FetchError: request to https://dev.coda.io:8080/apis/v1/packs/2000000024/versions/2.3/register failed, reason: unable to verify the first certificate
at ClientRequest.<anonymous> (/Users/alanfang/code/packs-sdk/node_modules/node-fetch/lib/index.js:1461:11)
at ClientRequest.emit (events.js:315:20)
at ClientRequest.EventEmitter.emit (domain.js:467:12)
at TLSSocket.socketErrorListener (_http_client.js:469:9)
at TLSSocket.emit (events.js:315:20)
at TLSSocket.EventEmitter.emit (domain.js:467:12)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
type: 'system',
errno: …
```
=> Add action prompt when dev certs are rejected

Makefile, runtime/isolated-vm/isolated-vm.js, runtime/isolated-vm/package.json
per slack discussion, we want to build an isolated-vm binary that's compatible with lambda instance type (i.e. amazon linux 2). 
the 3 files in `runtime/isolated-vm/` are basically all we need for lambda functions to use isolated vm. 
@chris-codaio after thinking about this again, it seems better to build this binary file in the primary coda repo with `make build-packs-runtime`. what do you think?
=> build isolated binary that runs on amazon linux 2

cli/config_storage.ts, dist/cli/config_storage.js, dist/testing/auth.js, dist/testing/helpers.d.ts, dist/testing/helpers.js, testing/auth.ts, testing/helpers.ts
This came up in NCC's review as a minor race condition, where the credentials are written to a world-readable file ever briefly before chmod happens to restrict the file to the current user only.
The social engineering attack that they alluded to briefly was actually a bit more interesting to me, if somebody shares pack boilerplate with you that already has a .coda.json file, that's already world-readable, the existing code wouldn't update the permissions, so you could be engineered into storing credentials into a world-readable file. This changes things to always reset the mode before writing anything.
PTAL @huayang-codaio @patrick-codaio CC @chris-codaio @coda/packs
=> Always set the file mode first before writing credentials.

cli/register.ts, dist/cli/register.js
Totally forgot that the deep-linking was already implemented.
=> When registering an API token, deep link to the token modal and pre-select the Packs scope.

Makefile, cli/build.ts, cli/coda.ts, cli/execute.ts, dist/cli/build.d.ts, dist/cli/build.js, dist/cli/coda.js, dist/cli/execute.d.ts, dist/cli/execute.js, dist/runtime/bootstrap/index.js, dist/runtime/common/source_map.js, dist/testing/compile.d.ts, dist/testing/compile.js, dist/testing/execution.d.ts, dist/testing/execution.js, dist/testing/helpers.d.ts, dist/testing/helpers.js, dist/testing/injections/timers_disabled_shim.js, dist/testing/injections/timers_shim.js, runtime/bootstrap/index.ts, runtime/common/source_map.ts, test/packs/fake.ts, testing/compile.ts, testing/execution.ts, testing/helpers.ts, testing/injections/timers_disabled_shim.js, testing/injections/timers_shim.js
sending this out since it's getting bigger than I expected. basically a few necessary changes to help debugging v1 packs. 
- support a minify flag for CLI buid for debugging purpose. (easier to identify issues).
- add a timer method in the fake pack for debugging. (to debug setTimeout)
- add an extra level of esbuild for shim injection. (for setTimeout)
- translate error stack from loadIntoIVM (this happens)
- add shim for timing methods (i.e. setTimeout)
- don't build another bundle for exec-in-vm
I am adding `timers` as an option instead of the default because I still need to test esbuild for browserifying capability.
=> a few changes for debugging v1 packs

Makefile
leverage typedoc `gitRemote` option.
unfortunately it doesn't support passing a url so we have to create a special remote if one doesn't exist.
=> use a dedicated git remote to generate type docs

Makefile
realized that `git@github.com:coda/packs-sdk.git` is too restrict. 
ppl might be using `https://github.com/coda/packs-sdk.git` or `https://github.com/coda/packs-sdk`. let just check coda/packs-sdk exists.
testing:
```
➜  packs-sdk git:(hg-add-remote-to-build-docs) ✗ git remote -v 
origin  git@github.com:kr-project/packs-sdk.git (fetch)
origin  git@github.com:kr-project/packs-sdk.git (push)
➜  packs-sdk git:(hg-add-remote-to-build-docs) ✗ make typedoc  
Please config your git origin to git@github.com:coda/packs-sdk.git
make: *** [typedoc] Error 1
```
=> better handling or git remote

bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/thunk/thunk.js, runtime/thunk/thunk.ts
This is the cause of the error `Could not find a formula matching formula spec {"type":"Metadata","metadataFormulaType":"SyncGetSchema","syncTableName":"Issues"}` for Jira.
It's this weird kind of sync table that has a getSchema method, but doesn't have `isDynamic: true`. So it was returning false on the `isDynamicSyncTable()` check (which is just a TypeScript guard) and we weren't resolving a formula for it.
PTAL @huayang-codaio @alan-codaio @coda/packs
=> Fix thunk for sync tables like Jira Issues, which are not strictly dynamic but have dynamic schema.

cli/build.ts, dist/cli/build.d.ts, dist/cli/build.js, dist/testing/injections/timers_shim.js, test/execution_test.ts, testing/injections/timers_shim.js
Context for those not already in the discussion, our own Coda Internal pack makes a Coda API mutation request, and then needs to poll the getMutationStatus endpoint until the mutation is applied. It's using setTimeout() to do this today, to sleep in between hitting that endpoint. Future packs that do Coda API mutations may need this too, as well as user packs with similar constraints.
Alex found the suggestion of using `Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, timeout);` as a way to synchronously block in `node`. By adding this to our shim, we seem to get the best of both worlds, where the timeout is still respected, however because it's not actually scheduled at the system level at the system level, when the isolate times out and gets torn down, this blocking call …
=> Augment the setTimeout() shim to block synchronously before yielding with a Promise.

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Bug here: https://staging.coda.io/d/Packs-IA-go-packs_d36WK4zgrYx/Bugs-Feature-requests_suyN0#Open-Bugs_tu6FU/r132&modal=true
This PR enforces that all formula parameters (standard and vararg) have unique names. Although Tarunjeet's error came from parameters with autocomplete, duplicate parameter names are probably likely to break for a bunch of different types of parameters generally.
=> Enforce that formula parameters have unique names

docs/enums/AttributionNodeType.html, docs/enums/CurrencyFormat.html, docs/enums/DurationUnit.html, docs/enums/ValueHintType.html, docs/enums/ValueType.html, docs/interfaces/ArraySchema.html, docs/interfaces/BooleanSchema.html, docs/interfaces/CurrencySchema.html, docs/interfaces/DateSchema.html, docs/interfaces/DateTimeSchema.html, docs/interfaces/DurationSchema.html, docs/interfaces/Identity.html, docs/interfaces/IdentityDefinition.html, docs/interfaces/NumberSchema.html, docs/interfaces/NumericSchema.html, docs/interfaces/ObjectSchema.html, docs/interfaces/ObjectSchemaProperty.html, docs/interfaces/ScaleSchema.html, docs/interfaces/SliderSchema.html, docs/interfaces/StringSchema.html, docs/interfaces/TimeSchema.html
These got deleted as part of https://github.com/coda/packs-sdk/pull/1330 and I'm not sure why, thanks to Eric for catching this. Simply doing `make build` from the tip of main brings them back. 🤷 
PTAL @huayang-codaio @ekoleda-codaio @coda/packs
=> Put pack schema documentation files.

bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/common/marshaling/index.js, runtime/common/marshaling/index.ts, test/marshaling_test.ts
Fixes https://go/bug/19250. Specifically, the issue was caused by pack code that assumed that an un-set boolean param would be `undefined` when it came through as `null`. This happened because JSON has no native way to represent `undefined`, and so we hack.
=> Teach our marshaling the difference between null and undefined

Makefile, Pipfile, Pipfile.lock, mkdocs.yml
For the moment MkDocs is just serving the complete HTML that comes from TypeDoc, but that will be changed to markdown in a later PR. Out GitHub pages config will need to change to pull from gh-pages:/ instead of main:/docs.
=> Basic MkDocs setup

.gitignore, mkdocs.yml
The edit link was defaulting to the `master` branch instead of `main`. Also as per [notes in their guide](https://www.mkdocs.org/user-guide/configuration/#edit_uri), switched the edit link to `/blob` instead of `/edit` so that the user isn't forced into a GitHub login screen.
=> Fix the edit link

.circleci/config.yml, Makefile
In PR #1363 I attempted to disable CircleCI on the gh-pages branch. That approach failed because that branch doesn't contain the `.circleci/config.yml` file, and so the build fails with "No configuration was found in your project". 
As per [this forum thread](https://discuss.circleci.com/t/no-config-found-builds-marked-as-failed/24912/2), the suggest approach is to append `[ci skip]` to the commit message, which can be done using the `--message` argument to `mkdocs deploy`.
=> Fix Circle CI for gh-pages

cli/register.ts, dist/cli/register.js, docs/get-started/cli.md
Bug here: https://staging.coda.io/d/Packs-IA-go-packs_d36WK4zgrYx/My-Tasks_suDJO#View-of-My-Bugs_tu8_z/r196&modal=true
Our accounts page already has an abstraction that handles this! Tested by opening https://dev.coda.io:8080/account?openDialog=CREATE_API_TOKEN&scopeType=pack#apiSettings. 
https://user-images.githubusercontent.com/79662144/134059447-9c451e45-10ca-40f6-a1b9-aefcb1588433.mov
=> Auto scroll to API settings when opening account settings via `coda register`

dist/testing/validation.js, testing/validation.ts
Part of https://staging.coda.io/d/Packs-IA-go-packs_d36WK4zgrYx/Bugs-Feature-requests_suyN0#Open-Bugs_tu6FU/r61&modal=true, where if the id field returned by a formula was falsy (i.e. 0, ''), then the result validation would fail.
Now we only error out if the ID field is specifically empty (null or undefined).
=> Don't error out if falsy values are returned in the result object schema

api.ts, builder.ts, dist/api.d.ts, dist/api.js, dist/builder.d.ts, dist/builder.js, dist/bundle.d.ts, docs/reference/sdk/classes/PackDefinitionBuilder.md, docs/reference/sdk/functions/autocompleteSearchObjects.md, docs/reference/sdk/functions/makeDynamicSyncTable.md, docs/reference/sdk/functions/makeEmptyFormula.md, docs/reference/sdk/functions/makeFormula.md, docs/reference/sdk/functions/makeMetadataFormula.md, docs/reference/sdk/functions/makeParameter.md, docs/reference/sdk/functions/makeSimpleAutocompleteMetadataFormula.md, docs/reference/sdk/functions/makeSyncTable.md, docs/reference/sdk/functions/makeTranslateObjectFormula.md, docs/reference/sdk/functions/newPack.md, docs/reference/sdk/functions/simpleAutocomplete.md, docs/reference/sdk/interfaces/EmptyFormulaDef.md, docs/reference/sdk/interfaces/MetadataFormulaObjectResultType.md, docs/reference/sdk/interfaces/PackFormulaDef.md, docs/reference/sdk/interfaces/SimpleAutocompleteOption.md, docs/reference/sdk/interfaces/SyncFormulaResult.md, docs/reference/sdk/types/Formula.md, docs/reference/sdk/types/MetadataContext.md, docs/reference/sdk/types/MetadataFormula.md, docs/reference/sdk/types/MetadataFormulaResultType.md, docs/reference/sdk/types/PackFormulaMetadata.md, docs/reference/sdk/types/TypedPackFormula.md
Improves how they are displayed in the rendered docs. [Preview](https://coda-packs-sdk.readthedocs-hosted.com/en/ek-example/reference/sdk/functions/makeFormula/).
=> Put all in-line examples in code blocks

Makefile
https://github.com/coda/packs-sdk/pull/1417 is failing even though it does not pass `make bs; make build` test locally. This is because our `vaidate-no-changes` step in CI only does `compile` which doesn't actually try to generate docs. Changing to use also do the `docs` step.
validated that on that branch with this step it fails and doesn't without
@jonathan-codaio cc @coda/packs
=> fix validate no changes to do all commands that generate possible diff

dist/bundle.d.ts, dist/types.d.ts, docs/reference/sdk/interfaces/Format.md, documentation/generated/examples.json, types.ts
This is an intermediate state, we will eventually remove the ability to have Strings in this field.
Planned sequence:
- Merge this SDK update
- Update SDK in Coda app
- Update all existing Coda packs to use RegExp objects (with a careful release of the updates)
- Announce to pack beta devs that the String option is going away
- Remove the String option from matchers type
=> Allow RegExp objects in column matchers

CHANGELOG.md, cli/release.ts, dist/cli/release.js
Now that it's possible to have versionless manifests, we need to handle this edge case in `coda release` where a version is not supplied on the CLI nor is one supplied by the manifest. In this case we grab the latest Pack version and attempt to release that instead.
I wonder if we should just make the manifest an optional argument now?
Tested output:
```
ts-node ../packs-sdk/cli/coda.ts release manifest.ts 
No version specified in your manifest. Do you want to release the latest version of the Pack (0.0.2)? (y/n)
n
```
=> Add a prompt to release the latest version for `coda release` if one is not provided by the manifest or the CLI

dist/testing/injections/timers_disabled_shim.js, docs/guides/advanced/libraries.md, testing/injections/timers_disabled_shim.js
Fixed the flag name in the error message, as it was out of date.
Staged: https://coda-packs-sdk.readthedocs-hosted.com/en/ek-timers/guides/advanced/libraries/#shims
=> Document timer shims

documentation/theme/main.html
context: https://github.com/coda/infra/pull/2136#discussion_r731438563
this produces in every index.html page generated:
=> add noindex meta tag to docs while in testing

Makefile, scripts/tsdoc_progress.ts, tsconfig.json
Output looks like:
```
TemporaryBlobStorage                     Interface                      api_types.ts
storeBlob                                Method                         undefined
storeUrl                                 Method                         undefined
getConnectionName                        Property                       types.ts
getConnectionUserId                      Property                       types.ts
type                                     Property                       types.ts
DefaultValueType                         Type alias                     api_types.ts
ExternalObjectPackFormula                Type alias                     compiled_types.ts
ExternalPackFormat                       Type alias                     compiled_types.ts
```
Only 380 to go! …
=> Add a script that indicates which identifiers need TypeDoc documentation.

dist/runtime/bootstrap/index.js, runtime/bootstrap/index.ts, test/packs/fake_v2.ts, test/thunk_test.ts
This is a tricky bug. if the exported bundle has an export symbol `coda` or `pack`, it will conflict with the global symbol `coda` and `pack` and such confuses `registerBundle`. 
This PR adds `global.` prefix to make sure that the `registerBundle` is setting to the global symbol. (of course if the bundle has an export called global we are screwed. hopefully nobody would do so)
also adding a v2 pack for testing.
=> fix runtime bootstrap upon naming conflict

CHANGELOG.md, cli/coda.ts, cli/config_storage.ts, cli/set_option.ts, dist/cli/coda.js, dist/cli/config_storage.d.ts, dist/cli/config_storage.js, dist/cli/set_option.d.ts, dist/cli/set_option.js, dist/testing/compile.js, dist/testing/injections/timers_disabled_shim.js, testing/compile.ts, testing/injections/timers_disabled_shim.js
I tried to add this to the pack definition as discussed on Slack, but unfortunately there's a chicken-and-egg problem with that, because we can't reliably pull values out of the TS until after the bundle is built, but we need the timer strategy as an input to generate the build in the first place.
So since we already have a .coda-pack.json file per pack, I added the ability to store persistent options in that file, and read from that when doing the build.
=> Create a way to store build options in the .coda-pack.json file. Use it to store the timerStrategy.

.gitignore, CHANGELOG.md, Makefile, bundles/thunk_bundle.js, cli/upload.ts, dist/bundles/thunk_bundle.js, dist/cli/upload.js, dist/package.json, dist/runtime/bootstrap/index.d.ts, dist/runtime/bootstrap/index.js, dist/testing/compile.js, dist/testing/ivm_helper.js, package.json, runtime/bootstrap/index.ts, testing/compile.ts, testing/ivm_helper.ts
We used to manually add a closure when throwing a bundle into IVM context. 
```
const script = await isolate.compileScript(
`(() => { ${stubName} = (() => { ${bundle} \n return exports; })(); })()`,
{
filename: path,
},
);
await script.run(context);
```
The reason of doing so is that isolated-vm evaluation has a different behavior from loading / eval / requiring a module in NodeJS. Imagine that we have a simple module like this:
```
-> % cat test.js
'use strict';
function hello() {
console.log('hello world');
}
module.exports = hello;
```
When the code is `eval` or required in node, no symbol leaks to global. 
```
> require('./test')
[Function: hello]
> global.hello
undefined
> hello
Uncaught ReferenceError: hello is not defined
> module.hello
undefined
> const code = …
```
=> Switch to iife format for pack and thunk bundles

Pipfile.lock, mkdocs.yml, requirements.txt
- Disabled instant navigation, as it's been acting buggy.
- Made the top nav sticky, since it's annoying to scroll all the way to the top to get it to reappear.
- Updated the GitHub link icon and repo name.
Staged: https://coda-packs-sdk.readthedocs-hosted.com/en/ek-mkdocs/guides/blocks/formulas/
=> Small updates to the mkdocs configuration

docs/get-started/cli.md, docs/guides/advanced/authentication.md, docs/guides/advanced/cli.md, docs/guides/advanced/schemas.md, docs/guides/basics/data-types.md, docs/guides/blocks/sync-tables.md, docs/guides/troubleshooting.md, docs/index.md, documentation/theme/main.html, mkdocs.yml
To help shift the center of mass from the Coda doc to mkdocs, stub out some pages with links back to the Coda doc and TODOs to migrate the content. Also changed the term from "Packs SDK" to "Pack SDK" in a number of places to match branding decision.
Staged: https://coda-packs-sdk.readthedocs-hosted.com/en/ek-merge/
=> Stub out pages for migration

Makefile, test/typedoc_coverage_test.ts
=> Add a unittest that enforces that all entities reachable by TypeDoc have documentation.

compiled_types.ts, dist/bundle.d.ts, dist/compiled_types.d.ts, docs/reference/sdk/interfaces/ExternalPackVersionMetadata.md, docs/reference/sdk/types/ExternalPackFormat.md, test/packs/fake_v2.ts
`External` types are stringified and uploaded to s3. can't have regex type in it.
=> make format string[] in ExternalPackFormat

builder.ts, dist/builder.d.ts, dist/bundle.d.ts, docs/reference/sdk/classes/PackDefinitionBuilder.md, test/packs/fake_v2.ts
Very interesting bug: when `execute` returns a bad object type on an object formula, TS will complain about returning object on boolean, instead of pointing out that the returned object doesn't match the schema.
The reason is that 
addFormula is defined as 
```
addFormula<ParamDefsT extends ParamDefs, ResultT extends FormulaResultValueType, SchemaT extends Schema>(
definition: FormulaDefinitionV2<ParamDefsT, ResultT, SchemaT>,
): this {
```
where `FormulaDefinitionV2<ParamDefsT, ResultT, SchemaT>` is defined as 
```
export type FormulaDefinitionV2<
ParamDefsT extends ParamDefs,
ResultT extends FormulaResultValueType,
SchemaT extends Schema,
> = ResultT extends ValueType.String
? StringFormulaDefV2<ParamDefsT>
: ResultT extends ValueType.Number
? NumericFormulaDefV2<ParamDefsT>
: ResultT …
```
=> fix ambiguous execute return type

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
@ekoleda-codaio pointed out that providing a schema with garbage keys like:
```const MySchema = coda.makeObjectSchema({
type: coda.ValueType.Object,
properties: {
thing: {type: coda.ValueType.Number, foo: true},
},
id: "thing", // Which property above is a unique ID.
primary: "thing", // Which property above to display by default.
});
```
caused our diff checker to choke. I think the right thing is to allow the diff checker to ignore these unknown keys and to have the upload validation tester complain when it gets such a key. 
Ideally I think most, if not all of our Zod stuff should be `strictObject`, but I don't know if this breaks tests/error messages, so I'll send out these kinds of updates in smaller, more digestible PRs.
=> Make typing strict for object property schemas

dist/bundle.d.ts, dist/types.d.ts, docs/reference/sdk/interfaces/CustomAuthentication.md, docs/reference/sdk/interfaces/Format.md, docs/reference/sdk/interfaces/PackDefinition.md, docs/reference/sdk/interfaces/PackVersionDefinition.md, docs/reference/sdk/types/Authentication.md, docs/reference/sdk/types/BasicPackDefinition.md, docs/reference/sdk/types/SystemAuthentication.md, types.ts
Without the `{% raw %}` directives the surrounding `{{`'s were getting lost. I also reformatted the code to be max 80 chars, so it fits better on the web page.
Staged: https://coda-packs-sdk--1557.com.readthedocs.build/en/1557/reference/sdk/interfaces/CustomAuthentication/
=> Fix CustomAuthentication typedoc

CHANGELOG.md, dist/bundle.d.ts, dist/types.d.ts, docs/reference/sdk/interfaces/CustomAuthentication.md, docs/reference/sdk/interfaces/Format.md, docs/reference/sdk/interfaces/PackDefinition.md, docs/reference/sdk/interfaces/PackVersionDefinition.md, docs/reference/sdk/types/Authentication.md, docs/reference/sdk/types/BasicPackDefinition.md, docs/reference/sdk/types/SystemAuthentication.md, types.ts
Adding in the change log for `AuthenticationType.Custom`. will publish a new NPM version after this goes in
@coda/packs @jonathan-codaio @ekoleda-codaio
=> add changelog for custom auth type

dist/bundle.d.ts, dist/handler_templates.d.ts, dist/index.d.ts, docs/reference/sdk/README.md, docs/reference/sdk/functions/makeEmptyFormula.md, docs/reference/sdk/interfaces/EmptyFormulaDef.md, docs/reference/sdk/interfaces/ObjectArrayFormulaDef.md, docs/reference/sdk/interfaces/RequestHandlerTemplate.md, docs/reference/sdk/interfaces/ResponseHandlerTemplate.md, handler_templates.ts, index.ts, typedoc.js
This the very last part of the SDK that I think needs reference documentation.
This is a bit of a dumpster fire of a feature though, in terms of its understandibility, consistency, and completeness. I'm also complete fine saying that we hide this and say it's unsupported until we decide to invest in it more.
These allow you to define formulas for common fetcher tasks without writing code. It looks like it was part of the original packs code from about 3 years ago and I haven't personally worked with it before, I had to teach myself how this seems to work while writing this. We appear to use it for some early packs like Figma and GitHub.
The aspiration to allow people to write packs declaratively is reasonable and it's long been a goal of Coda to let people write packs who don't know how …
=> Add documentation for RequestHandlerTemplate and ResponseHandlerTemplate.

test/typedoc_coverage_test.ts
=> Test to enforce that we don't have broken @links.

dist/bundle.d.ts, dist/testing/upload_validation.js, dist/types.d.ts, docs/reference/sdk/interfaces/Format.md, testing/upload_validation.ts, types.ts
This will make format easier to use before we are able to get rid of `formulaNamespace` completely. 
after:
=> making format formulaNamespace optional

docs/embedded-snippets/snippets/parameter/array/boolean_array_parameter.html, docs/embedded-snippets/snippets/parameter/array/date_array_parameter.html, docs/embedded-snippets/snippets/parameter/array/html_array_parameter.html, docs/embedded-snippets/snippets/parameter/array/image_array_parameter.html, docs/embedded-snippets/snippets/parameter/array/number_array_parameter.html, docs/embedded-snippets/snippets/parameter/array/string_array_parameter.html, docs/embedded-snippets/snippets/parameter/boolean_parameter.html, docs/embedded-snippets/snippets/parameter/date_parameter.html, docs/embedded-snippets/snippets/parameter/html_parameter.html, docs/embedded-snippets/snippets/parameter/image_parameter.html, docs/embedded-snippets/snippets/parameter/number_parameter.html, docs/embedded-snippets/snippets/parameter/string_parameter.html, docs/samples/topic/parameter.md, documentation/.eslintrc.js, documentation/generated/examples.json, documentation/generated/snippets.json, documentation/snippets/parameter/array/boolean_array_parameter.ts, documentation/snippets/parameter/array/date_array_parameter.ts, documentation/snippets/parameter/array/html_array_parameter.ts, documentation/snippets/parameter/array/image_array_parameter.ts, documentation/snippets/parameter/array/number_array_parameter.ts, documentation/snippets/parameter/array/string_array_parameter.ts, documentation/snippets/parameter/boolean_parameter.ts, documentation/snippets/parameter/date_parameter.ts, documentation/snippets/parameter/html_parameter.ts, documentation/snippets/parameter/image_parameter.ts, documentation/snippets/parameter/number_parameter.ts, documentation/snippets/parameter/string_parameter.ts
This makes them easier to use within parameter arrays, where they are most likely to be used. Raised by @punit-codaio during a recent end-to-end review.
=> Use a comma to end the parameter snippets

api.ts, dist/api.d.ts, dist/bundle.d.ts, docs/reference/sdk/interfaces/Continuation.md
Relax continuation typing to support a nested hash.
See https://codaproject.slack.com/archives/C02ERJRBA21/p1638833332320300 for context.
=> Relax continuation typing to support a nested hash

CHANGELOG.md, cli/coda.ts, dist/bundle.d.ts, dist/cli/coda.js, dist/testing/oauth_server.js, dist/testing/upload_validation.js, dist/types.d.ts, docs/reference/sdk/interfaces/AWSAccessKeyAuthentication.md, docs/reference/sdk/interfaces/AWSAssumeRoleAuthentication.md, docs/reference/sdk/interfaces/CustomAuthParameter.md, docs/reference/sdk/interfaces/CustomAuthentication.md, docs/reference/sdk/interfaces/Format.md, docs/reference/sdk/interfaces/OAuth2Authentication.md, docs/reference/sdk/interfaces/PackDefinition.md, docs/reference/sdk/interfaces/PackVersionDefinition.md, docs/reference/sdk/interfaces/VariousAuthentication.md, docs/reference/sdk/interfaces/WebBasicAuthentication.md, docs/reference/sdk/types/Authentication.md, docs/reference/sdk/types/BasicPackDefinition.md, docs/reference/sdk/types/SystemAuthentication.md, docs/reference/sdk/types/SystemAuthenticationDef.md, testing/oauth_server.ts, testing/upload_validation.ts, types.ts
SDK side of changes to address https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/My-Issues_sud-l#My-issues_tui9H/r19756&modal=true. Sending the `coda` side shortly too.
@ekoleda-codaio what's the best way to test this--is there a Todoist example that would validate that this works out of the box?
PTAL @huayang-codaio @patrick-codaio @ekoleda-codaio @coda/packs
=> Support a configurable scope delimiter for OAuth2.

docs/guides/advanced/cli.md, docs/guides/advanced/testing.md
Migrating content from the Coda doc, mostly as-is with some minor updates. Split the CLI and testing content into two different pages.
Staged:
- https://coda-packs-sdk--1639.com.readthedocs.build/en/1639/guides/advanced/cli/
- https://coda-packs-sdk--1639.com.readthedocs.build/en/1639/guides/advanced/testing/
=> Add CLI and Testing guides

dist/testing/fetcher.js, test/auth_test.ts, testing/fetcher.ts
https://codaproject.slack.com/archives/C02ERJRBA21/p1640727998430700
otherwise password is set to undefined and thus we have `<password>:undefined` in the header. 
```
> var a = {x: 1, y: undefined}
undefined
> a
{ x: 1, y: undefined }
> var {x, y} = a
undefined
> y
undefined
```
=> let password fallback to empty space (to be consistent with coda repo)

docs/guides/advanced/fetcher.md, docs/guides/basics/parameters.md, docs/guides/blocks/sync-tables.md, docs/guides/troubleshooting.md
Based on some recent user support, some small updates:
- Noted that vararg parameters don't show in the structured builders - [link](https://coda-packs-sdk--1669.com.readthedocs.build/en/1669/guides/basics/parameters/#accepting-multiple-values)
- Noted that response headers are lowercased and most are redacted - [link](https://coda-packs-sdk--1669.com.readthedocs.build/en/1669/guides/advanced/fetcher/#headers)
- Clarified that only GET requests are cached - [link](https://coda-packs-sdk--1669.com.readthedocs.build/en/1669/guides/advanced/fetcher/#caching)
- Noted that sync tables can't be synced via a button or automation - [link](https://coda-packs-sdk--1669.com.readthedocs.build/en/1669/guides/blocks/sync-tables/#using-sync-tables)
- Added some troubleshooting tips for domains that …
=> Small documentation updates

dist/bundle.d.ts, dist/types.d.ts, docs/reference/sdk/interfaces/CustomAuthentication.md, types.ts
Fixes https://coda.github.io/packs-sdk/reference/sdk/interfaces/CustomAuthentication/ to match https://coda.github.io/packs-sdk/guides/advanced/authentication/#custom-tokens (which is the correct one). While I'm here, I changed the quotes to double quotes since Eric picked that for our documentation style guide.
=> Remove stray quotes from our custom auth example

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Just cleaning up some SDK-side validation that prevented this. The real meat of the change is on the `coda`, sending that now.
This is to support use cases like a Wordpress pack, where the domain is arbitrary and the user has to specify it as the endpoint domain, but the pack doesn't need to make requests to any other domain other than the endpoint. Seems like we don't need them to ask for approval in that case, and in fact, our currently approval mechanism is just to allow any network domain, which is worse from a security perspective.
PTAL @huayang-codaio @patrick-codaio @ekoleda-codaio @coda/packs
=> Don't trigger a validation error for missing network domains if the auth config requires an endpoint url.

docs/guides/advanced/authentication.md, docs/guides/troubleshooting.md
This was the last reference to the Packs Beta doc in the documentation. Not a 1:1 port, so feel free to comment on the content.
=> Migrate logging content to MkDocs

CHANGELOG.md, api_types.ts, dist/api_types.d.ts, dist/bundle.d.ts, dist/testing/upload_validation.js, docs/reference/sdk/enums/ConnectionRequirement.md, docs/reference/sdk/enums/NetworkConnection.md, docs/reference/sdk/enums/PrecannedDateRange.md, docs/reference/sdk/interfaces/BaseFormulaDef.md, docs/reference/sdk/interfaces/EmptyFormulaDef.md, docs/reference/sdk/interfaces/ExecutionContext.md, docs/reference/sdk/interfaces/FetchRequest.md, docs/reference/sdk/interfaces/FetchResponse.md, docs/reference/sdk/interfaces/Fetcher.md, docs/reference/sdk/interfaces/InvocationLocation.md, docs/reference/sdk/interfaces/Network.md, docs/reference/sdk/interfaces/ObjectArrayFormulaDef.md, docs/reference/sdk/interfaces/PackFormulaDef.md, docs/reference/sdk/interfaces/ParamDef.md, docs/reference/sdk/interfaces/Sync.md, docs/reference/sdk/interfaces/SyncExecutionContext.md, docs/reference/sdk/interfaces/SyncFormulaDef.md, docs/reference/sdk/interfaces/TemporaryBlobStorage.md, docs/reference/sdk/types/DefaultValueType.md, docs/reference/sdk/types/FetchMethodType.md, docs/reference/sdk/types/ParamDefs.md, docs/reference/sdk/types/ParamValues.md, docs/reference/sdk/variables/ValidFetchMethods.md, testing/upload_validation.ts
https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/My-Issues_sud-l#My-issues_tui9H/r20767&modal=true
A few sanity checks before removing this field:
- packs repo doesn't use this field. 
- the field isn't actually loaded into `coda/modules/common/packs/formula.ts:generateFormulaDefinitions`, which means that it's being used on client at this moment. 
- after trying load the hidden option into client (as in `generateFormulaDefinitions`), here are a few observations:
- hidden parameters will be hidden from the structured builder (e.g. a button). This behavior seems useless for third-party packs. It's currently only being used by https://github.com/coda/coda/blob/main/modules/common/packs/formula.ts#L147 as far as I can tell. This usage is directly related to packs. 
- it breaks the …
=> remove hidden option of the pack parameter

docs/get-started/cli.md, docs/guides/advanced/cli.md, docs/guides/troubleshooting.md
Incorporates some recent user feedback, specifically:
- A stronger default to installing the SDK locally, including showing all examples using `npx`.
- Clarifying the redirect URL used by `coda auth`.
- Making clearer the requirements imposed by `isolated-vm`.
=> More CLI information

cli/helpers.ts, cli/init.ts, dist/cli/helpers.d.ts, dist/cli/helpers.js, dist/cli/init.js, docs/get-started/cli.md, package.json, patches/mold-source-map+0.4.0.patch
This PR allows `coda init` to patch `mold-source-map` using the one from packs-example (https://github.com/coda/packs-examples/pull/94). This avoids deprecation warnings from this zombie package.
=> inject patches in `coda init`

.gitignore, dist/testing/constants.d.ts, dist/testing/constants.js, dist/testing/fetcher.js, dist/testing/oauth_server.d.ts, dist/testing/oauth_server.js, package.json, test/packs/fake_v2.ts, testing/constants.ts, testing/fetcher.ts, testing/oauth_server.ts, yarn.lock
according to https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/My-Issues_sud-l#My-issues_tui9H/r20745&modal=true, client-oauth2 doesn't work for some oauth providers since it passes client secret via headers. 
this PR replaces client-oauth2 with direct requests to oauth providers (logic dup'ed from the packs-auth service). 
tested by 
- todoist pack
- fake_v2 pack with google auth. 
- force injecting a refresh and make sure it works.
=> get rid of client-oauth2

docs/guides/basics/data-types.md
Remove the warning about them not working outside of sync tables, and improve some of the examples.
=> Update documentation on type formatting

CHANGELOG.md, cli/upload.ts, dist/cli/upload.js, dist/helpers/external-api/coda.d.ts, dist/helpers/external-api/coda.js, dist/helpers/external-api/v1.d.ts, dist/helpers/external-api/v1.js, helpers/external-api/coda.ts, helpers/external-api/v1.ts
To help with attribution of Pack version uploads, this PR sets the source as CLI for any Pack uploaded via our CLI tool.
=> Tag all Pack version uploads from CLI as PackSource.Cli

.gitattributes
There is a mixture of handwritten and auto-generated files in the `/docs` directory. Adjust the linguist settings to more narrowly target the generated portions.
=> More narrowly target linguist

mkdocs.yml
I noticed https://github.com/squidfunk/mkdocs-material/issues/3330 happening on our docs, which is caused by a backwards-incompatible change introduced in the latest version of mkdocs-material. Followed their [upgrade guide](https://squidfunk.github.io/mkdocs-material/upgrade/#pymdownxtabbed) to resolve the issue.
=> Update mkdocs config to fix bug

docs/guides/blocks/formulas.md, documentation/theme/main.html, mkdocs.yml
Improve the social cards for the documentation. Specifically, Slack wasn't showing the page's title in the card. Updated the social metadata to use the page's title (preferring the longer title in the h1) and the page's custom meta description (if defined).
Before and after:
=> Update social metadata

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
I am adding network domains to the add-connection UI dialog, except the coda api auth type. In which case, user would assume that it only talks to coda api.
However I realized that this is not enforced in our validation. 
@coda/packs @patrick-codaio
=> restrict coda-api-auth network domains

compiled_types.ts, dist/bundle.d.ts, dist/compiled_types.d.ts
We want to be able to show everything about a pack's network activity in listings.
=> Add OAuth TokenUrl to our pack metadata

.circleci/config.yml, Makefile
1. The `bootstrap-aws-context-creds-ci` make command is used in nearly every project repo, so I refactored it into an orb command for `utils`.
2. Noticed that some jobs weren't cancelling and it looks like the orb command is a bit bugged. This is also fixed in the latest orb version for `utils` 
Below is a really old job in `packs-sdk` that was never canceled automatically
Ran the deploy for this PR
https://app.circleci.com/pipelines/github/coda/packs-sdk/5435/workflows/635fe4d7-2411-4135-a4e1-00ea7f38ab18
=> Cleanup CircleCI config: update utils orb and use orb command to unpack AWS creds

docs/guides/advanced/fetcher.md, docs/guides/advanced/schemas.md, docs/guides/best-practices.md, docs/guides/blocks/sync-tables/index.md, docs/guides/development/cli.md
- [Handling multiple header values](https://coda-packs-sdk--1795.com.readthedocs.build/en/1795/guides/advanced/fetcher/#headers)
- [Using `fromKey` with an existing schema](https://coda-packs-sdk--1795.com.readthedocs.build/en/1795/guides/advanced/schemas/#object-mapping)
- [More best practices](https://coda-packs-sdk--1795.com.readthedocs.build/en/1795/guides/best-practices/#sync-tables)
- [Sync table behavior when row limit hit](https://coda-packs-sdk--1795.com.readthedocs.build/en/1795/guides/blocks/sync-tables/#row-limits)
- [Migrating from the Web IDE to the CLI](https://coda-packs-sdk--1795.com.readthedocs.build/en/1795/guides/development/cli/#migrating-from-the-web-ide)
=> Various small doc improvements

docs/guides/advanced/fetcher.md, docs/guides/basics/data-types.md
- Document the outbound IP addresses Packs use.
- Clarify that percentage values should return a fraction (0.5) not a whole number (50).
- Include the new `StringEmbedSchema` in the formatting options section.
=> Small doc updates

docs/support.md
Today we renamed the category on the community to "Making Packs" to make the topic clearer. Updating the support page to point to the new name.
=> Update community category

cli/coda.ts, cli/create.ts, cli/link.ts, cli/release.ts, cli/upload.ts, dist/cli/coda.js, dist/cli/create.js, dist/cli/link.d.ts, dist/cli/link.js, dist/cli/release.js, dist/cli/upload.js, test/cli_test.ts
Updates .coda-pack.json to point at a pre-existing Pack that was created in the browser.
=> Add "link" command to associate with an existing Pack ID.

CHANGELOG.md, cli/coda.ts, cli/create.ts, cli/link.ts, cli/release.ts, cli/upload.ts, cli/whoami.ts, dist/cli/coda.js, dist/cli/create.js, dist/cli/link.js, dist/cli/release.js, dist/cli/upload.js, dist/cli/whoami.d.ts, dist/cli/whoami.js, package.json, test/cli_test.ts
Test plan:
Ran `npx ts-node ./cli/coda.ts whoami`, `npx ts-node ./cli/coda.ts whoami <valid token>`, and  `npx ts-node ./cli/coda.ts whoami <invalid token>`
I haven't tested a variety of token types (scoped vs non-scoped)
=> "whoami" command for determining the owner of the API token

CHANGELOG.md, cli/clone.ts, cli/coda.ts, dist/cli/clone.d.ts, dist/cli/clone.js, dist/cli/coda.js, package.json
The behavior is similar to "coda init", but additionally:
- Downloads typescript code if the existing pack was created in a web browser
- Prompt to overwrite if pack.ts already exists.
- If the existing pack wasn't created in a browser, prompt to initialize a template pack.ts
and also set up .coda-pack.json
- Set the Pack ID in .coda-pack.json, avoiding the need for a separate run of "coda link"
Test strategy:
- "coda clone <pack ID>" with a bad pack ID (error message about access)
- "coda clone <pack ID>" with a good pack ID (works)
- "coda clone --packVersion <version> <pack ID>" with a good pack ID (works)
- "coda clone <pack ID>" with a good pack ID and an SDK-written build (prompts to continue without source code)
- "coda clone <pack ID>" when pack.ts already exists (prompts to …
=> Add "coda clone <packIdOrUrl>"

.circleci/config.yml
realizing the `release` branch flow is a big pain to work with and with Github tags/releases that we're going to start using to tag new NPM releases i don't see the need for it. 
Instead, the new flow gives the option for any commit on main to deploy docs, as long as you first approve the doc deploy flow. It still maintains the extra approval to deploy to prod so you can manually verify on head/staging that docs are updated appropriately.
cc @coda/packs  @ekoleda-codaio @jonathan-codaio
=> make deploy docs available on any commit to main

package.json
Oops!  I set my version to "Unreleased" in the change log, but forgot to roll it back in package.json.  Hope this temporary hiccup doesn't hose anything!
=> Roll version back to 0.8.2 since 0.9.0 is unreleased

.circleci/config.yml, Makefile, docs/guides/blocks/sync-tables/index.md
mkdocs logs a warning when you link to a non-existent file. This change makes that warning an error, and builds the docs as part of the normal build process. 
```sh
INFO     -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '',
'on_undefined': 'keep', 'verbose': False}
INFO     -  [macros] - Extra variables (config file): ['social', 'coda']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /Users/EricKoleda/code/packs-sdk/site
WARNING  -  Documentation file 'guides/blocks/sync-tables/index.md' contains a link to …
```
=> Build docs in strict mode

docs/guides/development/cli.md, docs/guides/development/testing.md
Clarify how to pass multiple parameters, array parameters, and the lack of comma escaping.
=> Clarify passing parameters with CLI

docs/guides/development/cli.md, docs/samples/.nav.yml, docs/tutorials/get-started/cli.md, docs/tutorials/get-started/web.md
Given the [recent PR](https://github.com/coda/packs-examples/pull/130) to trim down the template Pack, this PR adds some more visibility to the recommended file structure:
- Documents it in the CLI guide.
- Adds a callout to that guide, and the packs-examples repo, at the end of the CLI getting started guide.
Adds a next steps section to the end of the Pack Studio getting started guide as well, for consistency.
=> Improve visibility of recommended pack file structure

.github/actions/release.yml, Makefile
also allows for release type input
apparently it doesn't show up in the "Actions" tab unless you configure it to run on `workflow_dispatch`
=> update workflow to run via manual trigger

docs/guides/basics/data-types.md
Multiple users have been confused about how to return an array of objects. Added this to the Data types guide, plus:
- Included sections for `String`, `Number`, and `Boolean` for completeness.
- Moved the `Object` section earlier, so I had already discussed object before I talk about arrays of objects.
=> Document array of objects

docs/guides/advanced/authentication.md
Document the behavior when you set an endpoint in your auth but don't list any network domains.
=> Document flexible endpoint domains

dist/runtime/common/helpers.js, runtime/common/helpers.ts
https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/Bugs_sucBW#Bugs_tuq-W/r19750&view=modal
after thinking about this again, I feel like it was a mistake to attempt looking up sync table by identity name. They are two separate things. 
PTAL @jonathan-codaio @coda/packs
=> allow look up sync table by identity name

CHANGELOG.md, dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
@jonathan-codaio @coda/packs PTAL
Since the UI does not currently support varargs in this context, just throw an error until we can fix it.
=> Add validation rule preventing usage of varargParameters for sync tables

docs/assets/custom.css, docs/guides/development/.nav.yml
Guide is already written in the help center documentation, linking off to it. Added a `.nav.yml` to link to it, and sorted the section alphabetically while I was there. Also addd some CSS to style an external link icon for nav items that link outside the SDK docs. The MkDocs Material theme we use embeds SVG icons in the CSS directly, so following that pattern here as well.
=> Add link to sharing and publishing guide

bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/common/marshaling/index.js, runtime/common/marshaling/index.ts
https://codaproject.slack.com/archives/C02K6EABVMK/p1649435284318259
turns out there's a legit case that Pack may return deep nested object. 
@jonathan-codaio @alan-codaio @coda/packs
=> skip marshaling deep-nested value instead of throwing

docs/guides/advanced/authentication.md, docs/guides/advanced/embeds.md, docs/guides/basics/parameters/index.md, docs/guides/best-practices.md, docs/guides/blocks/formulas.md, docs/guides/blocks/sync-tables/index.md, docs/guides/development/troubleshooting.md, docs/guides/faq.md
A bunch of small doc improvements I've been accumulating:
- How to request additional iframe permissions for an embed.
- Hosted image URLs are temporary.
- The fetcher can automatically access the `codahosted.io` domain.
- Add `getConnectionName()` as a best practice.
- Clarify formula caching behavior.
- Add troubleshooting section for response too larger errors.
- Document Google OAuth verification limitation.
=> Misc doc improvements

package.json
PTAL @huayang-codaio @patrick-codaio @dweitzman-codaio @coda/packs
=> Bump the SDK version number so that yarn won't resolve packs-sdk-for-web-editor the same commit hash accidentally.

dist/testing/upload_validation.d.ts, dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Will update things on the `coda` side in my pending change to call this to generate warnings.
=> Check for deprecated field names in object schemas. Add a warning mode for validation that applies all schema extensions.

cli/coda.ts, cli/validate.ts, dist/cli/coda.js, dist/cli/validate.d.ts, dist/cli/validate.js, setup-env.sh
To finish this off, we should next read the server-generated deprecation warnings that come back in the API response from `coda upload` and render those too. But this is helpful to allow people to (eventually) check most things for themselves locally. The major issue though is that if they're on an SDK version before this is supported, the ability to check for deprecation warnings locally doesn't exist, and so they would only know they're using deprecated stuff when `coda upload` tells them.
=> Show deprecation warnings in coda validate.

cli/upload.ts, dist/cli/upload.js, dist/helpers/external-api/coda.d.ts, dist/helpers/external-api/coda.js, dist/helpers/external-api/v1.d.ts, dist/helpers/external-api/v1.js, helpers/external-api/coda.ts, helpers/external-api/v1.ts
Should be the last piece of the puzzle. Makes the CLI show the same output as the web editor when uploading a new pack version if the server determines there are deprecation warnings. In theory this is the same output as what `validateMetadata()` with `checkDeprecationWarnings: true` would return locally, but we should consider the server authoritative in case we add server-side only checks.
All the changes are in `upload.ts`. The rest is just bringing the API codegen up to date to get the new type def that includes deprecation warnings on the upload response.
PTAL @dweitzman-codaio @patrick-codaio @coda/packs
=> Show server-generated deprecation warnings at the end of coda upload.

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Our intent is that our next SDK version will expose the new fields and allow for a transition period, and 2 releases from now is when we would actually start enforcing them, so we need our semver filters to reflect that.
PTAL @dweitzman-codaio @huayang-codaio @alexd-codaio @coda/packs
=> Don't hard fail on breaking changes until future version 1.0.0.

.circleci/config.yml, Makefile, typedoc.js
This is defense against the documentation links getting out-of-date every time
the types get updated in code.
Not 100% sure how to test this with circleci, but I tested the command locally
Testing:
Built with circleci on a devbox (mac OS was having a docker issue) and also changed the build command to this because I wasn't seeing output files saved anywhere on local disk:
```
DOC_GIT_REVISION="$(git rev-parse HEAD)" make docs && grep types.ts docs/reference/sdk/types/SystemAuthentication.md
```
This output printed shows that the new code is working (the commit hash is from this PR):
```
[types.ts:636](https://github.com/coda/packs-sdk/blob/e31687b1ca6b8940422948d7c1ddbf83b4f91ebd/types.ts#L636)
```
=> Link to specific commit hashes from reference documentation

docs/support/index.md
We relocated the Making Packs category in Discourse, which requires us to fix some metadata on the support page.
=> Update community info

CHANGELOG.md, docs/support/migration/v0.11.0.md
s/net/set/ in "For affected Packs, net the networkDomain field..."
Also removed a newline in the changelog that wraps a line early
All the other changes were automatically made by my format-on-save settings
in vscode. Using "**" instead of "__" for bold text does seem more common
in the rest of the codebase, but also happy to revert those changes (I really
just wanted to fix the typo).
=> Fix a super minor typo in the migration guide

CHANGELOG.md, dist/bundle.d.ts, dist/testing/upload_validation.js, dist/types.d.ts, docs/reference/sdk/interfaces/AWSAccessKeyAuthentication.md, docs/reference/sdk/interfaces/AWSAssumeRoleAuthentication.md, docs/reference/sdk/interfaces/BaseAuthentication.md, docs/reference/sdk/interfaces/CodaApiBearerTokenAuthentication.md, docs/reference/sdk/interfaces/CustomAuthParameter.md, docs/reference/sdk/interfaces/CustomAuthentication.md, docs/reference/sdk/interfaces/CustomHeaderTokenAuthentication.md, docs/reference/sdk/interfaces/Format.md, docs/reference/sdk/interfaces/HeaderBearerTokenAuthentication.md, docs/reference/sdk/interfaces/MultiQueryParamTokenAuthentication.md, docs/reference/sdk/interfaces/OAuth2Authentication.md, docs/reference/sdk/interfaces/PackDefinition.md, docs/reference/sdk/interfaces/PackVersionDefinition.md, docs/reference/sdk/interfaces/QueryParamTokenAuthentication.md, docs/reference/sdk/interfaces/VariousAuthentication.md, docs/reference/sdk/interfaces/WebBasicAuthentication.md, docs/reference/sdk/types/Authentication.md, docs/reference/sdk/types/BasicPackDefinition.md, docs/reference/sdk/types/SystemAuthentication.md, docs/reference/sdk/types/SystemAuthenticationDef.md, test/upload_validation_test.ts, testing/upload_validation.ts, types.ts
While uncommon, some APIs do seem to require the same credentials to be used across multiple domains.
An example would be the Google Drive API, which serves thumbnail images off a different domain than file metadata but still requires thumbnail requests to send credentials.
The change here is to modify the type of the authentication `networkDomain` from `string` to `string | string[]` and update `upload_validation.ts` accordingly.
=> Allow multiple auth domains

cli/build.ts, cli/coda.ts, dist/cli/build.d.ts, dist/cli/build.js, dist/cli/coda.js
when I was adding https://github.com/coda/coda/pull/71606, I realized that without setting the intermediate directory, the output isn't stable after each build because a randomly generated temp directory will go into source map & source code. 
this PR adds the option for `coda build`. 
=> add intermediateOutputDirectory option for coda build

documentation/generated/examples.json, documentation/scripts/documentation_compiler.ts
As discovered during today's SME Talk, the footer links for some sample still link out to GH pages. Updated the code to use the correct URL. CC @punit-codaio @alicia-codaio.
=> Fix base URL for footer links

docs/guides/advanced/authentication.md
The file `authentication.md` was touched in PR #1907 and it looks like an auto-formatter went awry. Our documentation is using some plugins that introduce non-standard markdown syntax that broken when reformatted.
I used the approach [documented here](https://stackoverflow.com/a/7196615) to revert the change to this file.
=> Undo bad auto-formatting

docs/assets/custom.css
The drop shadows on the screenshots were being clipped on the side in the tutorial. Couldn't find an easy way to size the images to prevent that, so using a border for those cases instead.
Before:
After:
=> Fix screenshot style in tutorials

compiled_types.ts, dist/bundle.d.ts, dist/compiled_types.d.ts
`networkDomain` can also be an array now
=> Fix external metadata auth network domain type

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Auth network domains are optional until a future SDK release, but if someone
chooses to set them now we still want to ensure the value they choose matches
a pack network domain
=> Fix validation of auth network domains

docs/guides/advanced/two-way-sync.md, docs/guides/blocks/actions.md, docs/guides/blocks/sync-tables/dynamic.md, docs/guides/blocks/sync-tables/index.md
I wanted to add the new information about `includeUnknownProperties` and dynamic URLs, but the content was getting a bit too long for its existing home in the actions page. Broke it out to a new advanced guide on two-way sync. In the future it would be nice to add more information to that page on how to setup a doc/template using the patterns @punit-codaio developed for the Jira Pack, but I don't consider that blocking.
Staged here: https://coda-packs-sdk--2010.com.readthedocs.build/en/2010/guides/advanced/two-way-sync/
=> Create guide on two-way sync

.npmignore
There are some animated .gif files in the documentation that account for nearly all of the node module size.
Tested by running `npm pack` and observing that the docs/ and site/ directories were omitted from the generated tarball
=> Exclude documentation from the packs sdk npm to save 100mb

CHANGELOG.md, bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/common/marshaling/marshal_buffer.js, runtime/common/marshaling/marshal_buffer.ts, test/compile_test.ts, test/packs/fake.ts, test/packs/fake_v2.ts
https://golinks.io/bug/21508
Though both the web editor build and the CLI build may include multiple instances of Buffer shims, the CLI build runs into the situation where thunk.js doesn't recognize the Buffer shim from `bundle.js`. This is a bug that we are just lucky it works in web. 
This PR fixes the issue by using buffer shim's `isBuffer` for type checking. 
Tested for both the web build and CLI build that this works. Added a unittest and verified that it failed before this PR.
PTAL @jonathan-codaio @ekoleda-codaio
=> fix marshalBuffer in CLI

.github/workflows/release.yml, .gitignore, Makefile
spent a bit of time investigating this flow after going through it with @dweitzman-codaio and updating to at least have a single command that we can run manually along with some instructions on how to do so.
https://staging.coda.io/d/Packs-Platform-IA-o-packs_d36WK4zgrYx/Releasing-Packs-SDK-Versions_suerz#_luCH6
here's a video of what it looks like (the command is now `make release-manual`)
https://www.loom.com/share/9e85cf7638434e8d8feb1f242a8616e9
The automated flow still won't quite work because it needs to be set up with some NPM tokens and such, but I think that's something we can tackle down the line as we get more rigorous with regular deployment
@coda/packs @jonathan-codaio
=> add manual release flow step

CHANGELOG.md, dist/testing/constants.d.ts, dist/testing/constants.js, dist/testing/fetcher.js, testing/constants.ts, testing/fetcher.ts
For https://coda-final.oslash.com/o/bug/23665
Verified this works with
```import * as coda from "@codahq/packs-sdk";
export const pack = coda.newPack();
// Regular expression that matches Coda-hosted images.
const HostedImageUrlRegex = new RegExp("^https://(?:[^/]*\.)?codahosted.io/.*");
// Formula that calculates the file size of an image.
pack.addFormula({
name: "FileSize",
description: "Gets the file size of an image, in bytes.",
parameters: [
coda.makeParameter({
type: coda.ParameterType.Image,
name: "image",
description:
"The image to operate on. Not compatible with Image URL columns.",
}),
],
resultType: coda.ValueType.Number,
execute: async function ([imageUrl], context) {
// Throw an error if the image isn't Coda-hosted. Image URL columns can
// contain images on any domain, but …
```
=> add default allowed get domains

dist/bundle.d.ts, dist/schema.d.ts, dist/schema.js, dist/testing/upload_validation.js, docs/reference/sdk/enums/core.AttributionNodeType.md, docs/reference/sdk/functions/core.generateSchema.md, docs/reference/sdk/functions/core.makeAttributionNode.md, docs/reference/sdk/functions/core.makeObjectSchema.md, docs/reference/sdk/functions/core.makeReferenceSchemaFromObjectSchema.md, docs/reference/sdk/functions/core.makeSchema.md, docs/reference/sdk/functions/core.withIdentity.md, docs/reference/sdk/interfaces/core.Identity.md, docs/reference/sdk/interfaces/core.ImageAttributionNode.md, docs/reference/sdk/interfaces/core.LinkAttributionNode.md, docs/reference/sdk/interfaces/core.ObjectSchemaDefinition.md, docs/reference/sdk/interfaces/core.TextAttributionNode.md, docs/reference/sdk/types/core.AttributionNode.md, docs/reference/sdk/types/core.InferrableTypes.md, docs/reference/sdk/types/core.Schema.md, docs/reference/sdk/types/core.SchemaType.md, schema.ts, testing/upload_validation.ts
References across packs is now supported by https://github.com/coda/coda/pull/73551
=> Update comments now that we support references across Packs

package.json, yarn.lock
This PR resolves dependabot alerts:
* https://github.com/coda/packs-sdk/security/dependabot/11 [CVE-2022-33987](https://github.com/advisories/GHSA-pfrx-2q88-qq97)
* https://github.com/coda/packs-sdk/security/dependabot/12 [CVE-2022-33987](https://github.com/advisories/GHSA-pfrx-2q88-qq97)
`release-it@15.0.0` has a direct dependency on `got@12.0.4`.
Vulnerable version of got is pulled in through a transitive dependency.
`release-it@15.0.0` -> `package-json@6.5.0` -> `got@^9.6.0`
=> Force got package to version 12.1.0

docs/assets/custom.css, docs/tutorials/.nav.yml, docs/tutorials/build/fetcher.md, docs/tutorials/build/formula.md, docs/tutorials/build/oauth.md, docs/tutorials/get-started/cli.md, docs/tutorials/get-started/web.md, docs/tutorials/index.md
Uses the same logic as the Samples index page. Added icons and descriptions to the existing tutorials to power it.
Staged: https://coda-packs-sdk--2078.com.readthedocs.build/en/2078/tutorials/
=> Add tutorials landing page

package.json, yarn.lock
This PR resolves [dependabot alert 18](https://github.com/coda/packs-sdk/security/dependabot/18) [CVE-2022-0624](https://github.com/advisories/GHSA-3j8f-xvm3-ffx4).
=> Force parse-path to version 5.0.0

docs/guides/development/troubleshooting.md
Staged: https://coda-packs-sdk--2111.com.readthedocs.build/en/2111/guides/development/troubleshooting/#cant-upload-from-the-cli
=> Troubleshooting for old mac versions

CONTRIBUTING.md, Makefile, README.md, docs/assets/custom.css, docs/support/contributing/.nav.yml, docs/support/contributing/index.md, docs/support/contributing/style.md
Added a GitHub-standard `CONTRIBUTING.md` file with basic guidelines for contributing documentation changes. Also relocated some contributing information from the `README.md` to this new page.
Copied over the content from the original [sample code style guide](https://staging.coda.io/d/_d0_QypZAlFU/9-28-Sample-Code-Style-Guide_suCJo) into a page in the documentation, and referenced it in the contributing guide.
Staged:
- https://coda-packs-sdk--2117.com.readthedocs.build/en/2117/support/contributing/
- https://coda-packs-sdk--2117.com.readthedocs.build/en/2117/support/contributing/style/
=> Create contributing and style guides

docs/guides/advanced/.nav.yml, docs/guides/advanced/authentication/.nav.yml, docs/guides/advanced/authentication/index.md, docs/guides/advanced/authentication/oauth2.md, docs/guides/advanced/fetcher.md, docs/guides/best-practices.md, docs/guides/blocks/formulas.md, docs/support/migration/v0.11.0.md, docs/tutorials/build/oauth.md
Wanted to add more information about OAuth token refreshes and incremental auth prompts, and it was becoming too much for the existing Authentication guide. Broke our OAuth into a separate page and added that new information.
=> Create OAuth guide

CHANGELOG.md, dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
This is just earlier feedback to a pack developer if there's something wrong with the provided authorizationUrl or tokenUrl
As a side benefit, once all packs are running at the next SDK release or higher we can simplify validation rules involving the domains of these URLs on the server side because parse errors could be server errors instead of a user-facing request error.
=> Validate the authorizationUrl and tokenUrl are actually URLs

dist/testing/execution.js, testing/execution.ts
Identified when trying to help [a user in the community](https://community.coda.io/t/testing-dynamic-sync-formulas/32585), `newRealFetcherSyncExecutionContext` was calling itself instead of `newRealFetcherExecutionContext`, resulting in an endless loop.
=> Fix endless loop

CHANGELOG.md, dist/testing/upload_validation.d.ts, dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Adds length validation to:
- Building block names and descriptions
- Total building block count
- Column format matchers length
- Network domain url length and column format matcher regex length
PTAL @gary-codaio @jonathan-codaio @huayang-codaio
=> Add length validation to various fields that will be indexed

CHANGELOG.md, dist/testing/compile.js, test/packs/fake_v2.ts, testing/compile.ts
I realized that the platform='node' in the compiler only allows to use node modules. it will be browserified anyway later. 
maybe there's better way to make this work but let's unblock the sdk for now.
```
-> % npx ts-node cli/coda.ts build test/packs/fake_v2.ts            
Pack built successfully. Compiled output is in /var/folders/n1/7qfgvcqn04j0py98bvnsnd500000gp/T/coda-packs-114f3e2d-d4a2-4578-84f3-9f195b8924adwRX5AS/bundle.js
```
=> fix CLI compiler for using node modules.

package.json, yarn.lock
https://github.com/coda/packs-sdk/security/dependabot/19
not a big deal. we can't bump all node-fetch to 3+ because it isn't compatible with our API.
=> quick fix of security alert

docs/guides/advanced/schemas.md
fix typo: coda.ValeType.Number -> coda.ValueType.Number
=> Fix small typo in schemas.md

Makefile, cli/clone.ts, cli/link.ts, cli/register.ts, cli/release.ts, dist/cli/clone.js, dist/cli/link.js, dist/cli/register.js, dist/cli/release.js, dist/testing/auth.js, dist/testing/helpers.d.ts, dist/testing/helpers.js, package.json, test/auth_test.ts, test/helpers_test.ts, testing/auth.ts, testing/helpers.ts, yarn.lock
A developer noticed that [the documentation](https://coda.io/packs/build/latest/tutorials/get-started/cli/#register-an-api-token) said to enter `y` but that only `yes` was accepted. I noticed that the codebase was using a mix of `yes` and `y`, without the ability to convert between the two.
I updated the `promptForInput` helper function to include a special `yesOrNo` mode that used the `yn` NPM library to handle all the variations. I then updated the codebase to use the this new mode wherever a yes/no question was being asked.
I also added tests for this function, using the newly added `proxyquire` NPM library, as I couldn't get `sinon` to mock a lop-level export of a library.
=> Allow flexible yes/no responses in prompts

docs/support/index.md
small tweaks to the language to make it support the related case where oauth uses different domains for authorization and token url. 
@dweitzman-codaio @ekoleda-codaio @jonathan-codaio
=> tweak words to let people get help for oauth url domain mismatch

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Part of the fix for https://staging.coda.io/d/_d-GJF-DmEUK#Bugs_tuq-W/r25095&view=modal. Sliders schemas can have formulas for these attributes, our types already supported that but zod did not. So if you try to cross-doc a column that uses formulas for these, you'd hit a zod validation error in the cross-doc workflow.
I don't think we have any other examples of passing CFL in the SDK yet, so I don't think this is functionality we should advertise, but if we're just blindly passing through values from cross-doc, seems ok.
This doesn't fully fix the issue though, because there's a bug in the API, and the actual cell values for sliders that use formulas are structured values and the API is returning them as serialized JSON strings rather than numbers (and those JSON values don't even have …
=> Fix zod validation for slider min/max/step that are formulas.

package.json, yarn.lock
Resolve dependabot alerts for:
* https://github.com/coda/packs-sdk/security/dependabot/20 ([CVE-2022-2900](https://github.com/advisories/GHSA-j9fq-vwqv-2fm2))
* https://github.com/coda/packs-sdk/security/dependabot/21 ([CVE-2022-3224](https://github.com/advisories/GHSA-pqw5-jmp5-px4v))
=> Bump parse-url to version ^8.1.0

docs/samples/index.md, docs/tutorials/index.md
The Tutorials and Samples listing pages were using `page.title` to generate the card titles. However the changes in #2212 make that default to the H1 value, which can be a bit long and awkward in the card.
`mkdocs_hooks.py`, which corrects `page.title` using the `nav:` frontmatter field, runs after the `macros` plugin. Switching the order would introduce other potential problems, so instead adjusting the macro logic to use the `nav:` field as well. This reverts these pages back to how they were before #2212.
=> Use nav title for listing pages

docs/guides/faq.md
Now that we have found a path to Google OAuth verification, update the FAQ accordingly.
=> Update Google Verification FAQ

cli/init.ts, dist/cli/init.d.ts, dist/cli/init.js
I think git is installed by default on Macs but not on Windows. On Linux, varies with the distribution. Explains why errors running `coda init` cropped up as a "Windows bug".
PTAL @ekoleda-codaio @huayang-codaio @coda/packs
=> Exit with a helpful warning if coda init cannot be completed because git is not installed.

docs/guides/basics/data-types.md, docs/guides/development/cli.md, docs/tutorials/get-started/cli.md
- Reflect new schemas and hints in the Data types guide. Also [reformatted the tables](https://coda-packs-sdk--2236.com.readthedocs.build/en/2236/guides/basics/data-types/#column-types) a bit to consolidate information.
- Reflect that `isolated-vm` is now an optional dependency.
=> Update guides to reflect 1.1.0 changes

CHANGELOG.md, cli/coda.ts, cli/release.ts, dist/cli/coda.js, dist/cli/release.d.ts
Enforce CLI release to come with an initial release notes to best support the breaking changes story. 
PTAL @jonathan-codaio @patrick-codaio @alan-codaio  
cc @erickoledadevrel 
```
-> % npx ts-node cli/coda.ts release test/packs/fake_v2.ts 
coda.ts release <manifestFile> [packVersion]
Set the Pack version that is installable for users. You may specify a specific
version, or omit a version to use the version currently in the manifest file.
The version must always be higher than that of any previous release.
Options:
--version  Show version number                                   [boolean]
--help     Show help                                             [boolean]
-n, --notes    Notes about the contents of this Pack release
[string] [required]
Missing required argument: notes
Please …
```
=> make release notes required from CLI

Makefile, docs/index.md, docs/tutorials/index.md, docs/tutorials/webinars.md
Add page to collect videos of past webinars. Also:
- Fix the preview server not generating social cards.
- Add one webinar to the homepage.
=> Add webinars page

api.ts, dist/api.d.ts, dist/api.js, dist/bundle.d.ts, docs/reference/sdk/functions/core.autocompleteSearchObjects.md
See https://github.com/coda/packs-sdk/blob/main/api.ts#L1253-L1254
`search` query and `displayKey` prop of searched objects are both made lowercase, making the search case-insensitive (or non case-sensitive, feel free to rename).
=> Update core.autocompleteSearchObjects.md to correct inaccuracy

docs/guides/development/cli.md
Given the change in #2235, updated the CLI guide to reflect that the `--notes` argument is required.
=> Update CLI guide with required notes argument.

api.ts, bundles/thunk_bundle.js, dist/api.d.ts, dist/bundle.d.ts, dist/bundles/thunk_bundle.js, dist/index.d.ts, dist/runtime/bootstrap/index.js, dist/runtime/thunk/thunk.d.ts, dist/runtime/thunk/thunk.js, dist/testing/execution.js, index.ts, runtime/bootstrap/index.ts, runtime/thunk/thunk.ts, testing/execution.ts
* Cleanup thunk to take a hash instead of ordered params
* Export a generic version of the update payload type
PTAL @jonathan-codaio @huayang-codaio 
CC @coda/packs
=> [TwoWaySync] Tweak bootstrap for easier use

.release-it.json, CHANGELOG.md, Makefile, package.json, yarn.lock
Although [keepachangelog.com](https://keepachangelog.com) doesn't include a formal spec, tools have been built around it's recommended format ([example](https://github.com/oscarotero/keep-a-changelog)), resulting in an unofficial one. Our CHANGELOG wasn't parseable by those tools, since we didn't always follow the conventions.
This PR updates our CHANGELOG to bring it inline with the spec:
- All changes in bulleted lists.
- All changes grouped under h3's that indicate the type of change.
- All versions have a title (the part after the dash)
- Added version URLs (for versions that exist in GitHub)
Also adds a linter to make sure we stay in compliance, and adjusts the existing plugin to generate correct links.
=> Bring CHANGELOG inline with spec and add linter

.circleci/config.yml
seems like we need this to run `docker run`.
=> add setup_remote_docker

.circleci/config.yml
This is the token name used by the slack orb provided by CircleCI. We can standardize on that.
PTAL https://github.com/orgs/coda/teams/internal-tools
=> Use standard slack token name

Pipfile, Pipfile.lock
Resolve dependabot alerts:
* https://github.com/coda/packs-sdk/security/dependabot/23 ([CVE-2022-45199](https://github.com/advisories/GHSA-q4mp-jvh2-76fj))
* https://github.com/coda/packs-sdk/security/dependabot/24 ([CVE-2022-45199](https://github.com/advisories/GHSA-q4mp-jvh2-76fj))
@coda/infosec @jonathan-codaio
=> Bump pip:pillow to version 9.3.0

dist/testing/validation.js, test/validation_test.ts, testing/validation.ts
Relax URL validation to accept `data:` URLs (not just http/https)
We already use `data:` urls in ImageAttachment fields in the Google Drive pack – this change makes it so validation passes when testing locally using `coda execute`.
- Updated validation unit tests
- Tested this locally with `coda execute` on the google drive pack. Verified that with the change, we no longer get a URL validation error.
=> Relax URL validation to accept data: URLs (not just http/https)

package.json, yarn.lock
Resolves dependabot alert: https://github.com/coda/packs-sdk/security/dependabot/25
=> Bump npm:qs to version ^6.5.3

bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/thunk/thunk.js, runtime/thunk/thunk.ts, test/upload_validation_test.ts
The `switch` just flags in a nice way where you need to update when adding a new metadata formula type.
The tests are kind of only accidentally working right now, they're treating a raw pack def as metadata, and just coincidentally don't happen to be using or inspecting any fields that get transformed during metadata compilation. If your pack def uses a field whose compiled type is different you'll get a TS error. You'd similarly see weirdness if you made any assertions here. So just actually compiling the inputs so everything lines up as it should.
=> Some cleanup noticed during hackathon.

Pipfile.lock
Addresses https://github.com/coda/infra/security/dependabot/5
=> Bump certifi from 2022.9.24 to 2022.12.7

package.json, yarn.lock
Working around https://staging.coda.io/d/_d-GJF-DmEUK#Bugs_tuq-W/r26524&view=modal
There appears to be a bug in 4.4.2. For whatever reason, my installs are still using 4.4.1 so I don't run into this, but it seems like other people are getting 4.4.2 by default.
There aren't a lot of commits in https://github.com/laverdet/isolated-vm/commits/main between the versions, so it's almost certainly the case that https://github.com/laverdet/isolated-vm/commit/dba2aceae18d45106bad1ae0546a6274a38bc7d6 broke something. https://github.com/laverdet/isolated-vm/commit/905abbe0c36f6c143c3512173636443452b024be is a follow-on fix that may or may not address this issue, but there isn't a new patch version out to test with.
Regardless, let's just make sure people who depend on us don't wind up getting 4.4.2. …
=> Avoid isolated-vm version 4.4.2.

docs/reference/changes.md, docs/support/.nav.yml, docs/support/changes.md, docs/support/faq.md, docs/support/migration/index.md, mkdocs.yml
I've found myself looking for this information in the support section, and I think it makes more sense for it to live there. Added redirects in case it's been linked to from elsewhere.
=> Move some pages to the support section

.github/dependabot.yml
PTAL @coda/packs 
Context: https://codaproject.slack.com/archives/C02K6EABVMK/p1673043621769529
=> Ignore esm only module versions for yn and node-fetch

docs/tutorials/get-started/.cli/core.md
It's already included in the `.gitignore` file, so the warning is a bit overkill.
=> Remove gitignore warning

docs/index.md, docs/tutorials/get-started/.cli/core.md, docs/tutorials/get-started/github.md, docs/tutorials/get-started/gitpod.md, docs/tutorials/get-started/replit.md
Also includes these new tutorials on the home page and makes some minor tweaks to other tutorials.
[Preview](https://coda-packs-sdk--2444.com.readthedocs.build/en/2444/tutorials/get-started/gitpod/)
=> Add a Gitpod tutorial

.github/ISSUE_TEMPLATE/config.yml
Instead, forward users to our forum, help center, and bug bounty locations where we can help them.
Not sure if this will completely work, but giving it a try.
=> Attempt to limit/block external collaborators from opening issues

dist/documentation/types.d.ts, dist/documentation/types.js, docs/guides/blocks/cards.md, docs/samples/topic/card.md, documentation/example_page_template.md, documentation/generated/examples.json, documentation/samples/packs/card/README.md, documentation/scripts/documentation_compiler.ts, documentation/scripts/documentation_config.ts, documentation/types.ts
Given that cards will be in beta for a while longer, add clarification to the documentation. Adds an "under construction" icon in the nav and a warning on the pages.
Preview: [Guide](https://coda-packs-sdk--2453.com.readthedocs.build/en/2453/guides/blocks/cards/), [Samples](https://coda-packs-sdk--2453.com.readthedocs.build/en/2453/samples/topic/card/)
=> Add beta warning to Cards docs and samples

CHANGELOG.md, cli/clone.ts, cli/coda.ts, cli/create.ts, cli/helpers.ts, cli/link.ts, cli/release.ts, cli/upload.ts, dist/cli/clone.d.ts, dist/cli/clone.js, dist/cli/coda.js, dist/cli/create.d.ts, dist/cli/create.js, dist/cli/helpers.d.ts, dist/cli/helpers.js, dist/cli/link.d.ts, dist/cli/link.js, dist/cli/release.d.ts, dist/cli/release.js, dist/cli/upload.d.ts, dist/cli/upload.js
I've had at least two developers ask for this ([1](https://community.coda.io/t/apikey-environment-variable-instead-of-coda-json-file/37612?u=eric_koleda), [2](https://community.coda.io/t/feedback-on-passing-coda-api-key-as-a-command-line-argument-when-running-coda-upload-command/32748?u=eric_koleda)), to make it easier to set up auto-deployments of their Pack in a GitHub action. It was possible to work around this be generating a `.coda.json` file on the fly, but this is a lot simpler.
=> Add option to pass API token as CLI argument

dist/testing/injections/crypto_shim.js, test/packs/fake_v2.ts, testing/injections/crypto_shim.js
For environments using Node version >= 19.0.0, running any Coda CLI command would result in the following error:
```
TypeError: Cannot set property crypto of #<Object> which has only a getter
at ../../../packs/node_modules/@codahq/packs-sdk/dist/testing/injections/crypto_shim.js (/private/var/folders/50/_v53nyjd0vb2r94bzn5nbcqm0000gp/T/coda-packs-4ea73dfd-3391-4b5e-82f7-c91f11182216nGo4p5/bundle.js:148:21)
at __init (/private/var/folders/50/_v53nyjd0vb2r94bzn5nbcqm0000gp/T/coda-packs-4ea73dfd-3391-4b5e-82f7-c91f11182216nGo4p5/bundle.js:15:58)
at ../../../../../../private/var/folders/50/_v53nyjd0vb2r94bzn5nbcqm0000gp/T/coda-packs-4ea73dfd-3391-4b5e-82f7-c91f11182216nGo4p5/browserify-bundle.js (/private/var/folders/50/_v53nyjd0vb2r94bzn5nbcqm0000gp/T/coda-packs-4ea73dfd-3391-4b5e-82f7-c91f11 …
```
=> don't import our crypto shim if crypto is supported natively

package.json
This appears to avoid a regression in eslint performance when packs-sdk is imported at a newer commit hash
Don't ask me why.... I have no explanation
=> Bump version 1.2.3 -> 1.2.4

.github/workflows/stale.yml
I copied the workflow from one of the other repos. I'm not sure if other configuration would be needed to make this work, but it seems like the worst case scenario is that it does nothing
=> Add stale PR workflow to packs-sdk repo

setup-env.sh
Looks like Gary had to do this same thing last year in the `packs` repo, to get homebrew working properly so that you can install `yarn`. (Ideally we'd make all this hermetic.)
PTAL @gary-codaio @coda/packs
=> Homebrew path setup for Apple macs.

Makefile, package.json
To catch situations where a person (or a tool like renovate) hasn't updated `yarn.lock` before sending a PR
Tested by temporarily having a commit on this branch where package.json and yarn.lock don't match: https://app.circleci.com/pipelines/github/coda/packs-sdk?branch=dweitzman-yarn-frozen
=> Set --frozen-lockfile for yarn install on CI

package.json, yarn.lock
After doing this, "yarn audit" reports no dependencies with known security issues. Seems like the deps are sufficiently up-to-date that we don't need any explicit "resolutions" right now
=> Remove yarn "resolutions"

CONTRIBUTING.md
Google Cloud shell doesn't include `pnpm` installed, so updating the instructions to including installing it manually.
=> Update contributing instructions for pnpm

CHANGELOG.md, dist/testing/fetcher.js, testing/fetcher.ts
This was fixed on the server in o/bug/27140, but was still broken in the testing fetcher used locally.
=> Fix XML handling when `isBinaryResponse: true`

CHANGELOG.md, dist/testing/fetcher.js, testing/fetcher.ts
Fixes [bug-22180](https://go/bug/22180). Assigning to Chris since I think you're most familiar with this auth method.
=> Fix bug with AWS signatures in testing fetcher

bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/thunk/thunk.js, runtime/thunk/thunk.ts
This is necessary for the properties to show up in `Object.keys()` or a `for...in` loop
=> Define property autocomplete properties as "enumerable"

package.json
When I try to bump to this version in `coda`, `modules/server/base/test/static_error_pages_test.ts` fails with:
```
Error: global leak(s) detected: '__esDecorate', '__runInitializers', '__propKey', '__setFunctionName'
at Runner.checkGlobals (node_modules/.aspect_rules_js/mocha@10.2.0/node_modules/mocha/lib/runner.js:398:21)
at Runner.<anonymous> (node_modules/.aspect_rules_js/mocha@10.2.0/node_modules/mocha/lib/runner.js:165:12)
at Runner.emit (node:events:525:35)
at node_modules/.aspect_rules_js/mocha@10.2.0/node_modules/mocha/lib/runner.js:822:14
at done (node_modules/.aspect_rules_js/mocha@10.2.0/node_modules/mocha/lib/runnable.js:310:5)
at node_modules/.aspect_rules_js/mocha@10.2.0/node_modules/mocha/lib/runnable.js:371:11
```
I think it's now succeeding once I bump the semantic …
=> Try bumping patch version.

mkdocs.yml
In #2519 the MkDocs Material library was upgraded to a new major version, which introduced some [breaking changes](https://github.com/squidfunk/mkdocs-material/issues/4714). Namely, the click to copy button on code blocks and the edit source buttons are now opt-in. 
This PR re-enables those features, as well as takes advantage of the new view source button. Previously the edit button was being used to view the source, so the `edit_uri` has been fixed to that it opens the true edit URL and the new view source button has been enabled.
=> Fix breaking changes in MkDocs Material 9

docs/guides/basics/data-types.md
Embedding a doc I created to demonstrate how HTML and Markdown is rendered by a Pack.
[Preview](https://coda-packs-sdk--2571.com.readthedocs.build/en/2571/guides/basics/data-types/#markdown)
=> Add markup rendering examples.

CHANGELOG.md, dist/testing/fetcher.js, test/auth_test.ts, testing/fetcher.ts
=> Allow blank token prefixes for oauth.

Makefile, cspell.yml, docs/index.md, docs/tutorials/index.md, docs/tutorials/videos.md, mkdocs.yml
Wanted to include a [recent video](https://www.youtube.com/watch?v=z8J6kBxAod4) I made in the documentation.
- Featured it on the homepage, replacing the previous Todoist video.
- Added my last name to the custom dictionary used by the spellcheck lint.
- Renamed the webinars page to videos, to allow it to accommodate non-webinar videos.
- Added redirect.
- Added it to the videos page.
- Added a missing frontmatter description to the videos page.
- Added lint check for the existence of frontmatter.
=> Update videos in documentation.

api_types.ts, bundles/thunk_bundle.js, dist/api_types.d.ts, dist/bundle.d.ts, dist/bundles/thunk_bundle.js, dist/runtime/thunk/thunk.js, dist/runtime/types.d.ts, runtime/thunk/thunk.ts, runtime/types.ts
This seems like a simple and relatively future-friendly way to put the schema of the property currently being autocompleted somewhere a pack maker can easily access it.
There are still some unresolved questions about whether propertyName and syncTable.schema should or shouldn't be normalized, denormalized to the author-written values, or use the fromKey values when they're set, but this PR may buy us more time before we need to sort that out.
If we decide to start denormalizing schemas for the context it would change the `propertySchema` here, but we'd also have a breaking change with `context.syncTable.schema` to sort out.
=> Add "propertySchema" to PropertyAutocompleteFormulaSpecification

docs/assets/custom.css
MkDocs Material recently swapped out the search implementation, and the search suggestions can be very large, requiring a lot of scrolling to scan the results. It's a [known issue](https://github.com/squidfunk/mkdocs-material/issues/4278) and being worked on, but applying a workaround for now, [recommended](https://github.com/squidfunk/mkdocs-material/issues/4278#issuecomment-1562597537) by the author of MkDocs Material.
=> Fix search suggestion sizing

Makefile
Adapted the code from the `packs` repo. It's slower (no parallelization) but that's probably an OK tradeoff.
=> Fix bug with validate-samples not failing

renovate.json5
This is a follow-up to https://github.com/coda/packs-sdk/pull/2630
I'm not sure how to get `make _bootstrap-doc-tools` to work in the renovate container, but it's possible that building compiled JS files and typescript definitions will still work.
Failure error message example: https://github.com/coda/packs-sdk/pull/2637#issuecomment-1579226886
=> Skip building docs for renovate PRs

package.json, pnpm-lock.yaml
In https://github.com/coda/packs-sdk/pull/2629 I switched packs-sdk to a standalone pnpm install because pnpm requires a newer node version than the repo supports
An unintended side effect of using the standalone pnpm was that the node-gyp part of the isolated-vm install broke (https://github.com/pnpm/pnpm/issues/4347).
A workaround is to explicitly name node-gyp as a dev dependency of isolated-vm in package.json
=> Fix isolated-vm install with standalone pnpm

CHANGELOG.md, cli/config_storage.ts, dist/cli/config_storage.js
When running in codespaces containers are ephemeral so its much more natural to store this in its secret management solution
=> Fallback to reading api key from env var

dist/testing/upload_validation.d.ts, dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
This adds more performance/memory overhead, but the flexibility to do different validation based on SDK version seems important and validation doesn't happen all that frequently. Just when running `getSchema` for sync tables that use it and during pack upload
Also conditions the recently added `You must set "codaType" to ValueHintType.SelectList or ValueHintType.Reference when setting an "autocomplete" property.` on an SDK version greater than 1.4.0
Corresponding PR: https://github.com/coda/coda/pull/93495
=> Condition all zod validation on sdk version

docs/embedded-snippets/samples/packs/authentication/copper.html, docs/embedded-snippets/samples/snippets/authentication/user_multi_header.html, docs/guides/basics/authentication/index.md, docs/samples/topic/apis.md, docs/samples/topic/authentication.md, documentation/generated/examples.json, documentation/generated/pack.code-snippets, documentation/generated/snippets.json, documentation/samples/packs/authentication/copper.ts, documentation/samples/snippets/authentication/user_multi_header.ts, documentation/scripts/documentation_config.ts
Also removes the "Template" samples from the authentication samples. They confusingly still included the snippet placeholders, and they added little value.
Preview:
- https://coda-packs-sdk--2667.com.readthedocs.build/en/2667/guides/basics/authentication/#simple-tokens
- https://coda-packs-sdk--2667.com.readthedocs.build/en/2667/samples/topic/authentication/#multiple-headers
=> Add docs and samples for MultiHeaderToken

Pipfile, Pipfile.lock, docs/guides/basics/authentication/index.md, docs/guides/blocks/sync-tables/dynamic.md, docs/guides/blocks/sync-tables/index.md, docs/guides/blocks/sync-tables/two-way.md, docs/index.md, docs/tutorials/build/formula.md, docs/tutorials/get-started/.cli/core.md, docs/tutorials/get-started/.rebuild.md, docs/tutorials/get-started/.use.md, docs/tutorials/get-started/github.md, docs/tutorials/get-started/gitpod.md, docs/tutorials/get-started/replit.md, docs/tutorials/get-started/web.md, mkdocs.yml, requirements.txt
MkDocs was failing to build on M2 macs with the following error:
```
[info] Loaded plugin typedoc-plugin-markdown
[info] Documentation generated at ./docs/reference/sdk
Already has frontmatter: /Users/patrick/code/packs-sdk/docs/reference/sdk/index.md
INFO     -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [], 'render_by_default': True, 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '',
'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'on_undefined': 'keep', 'on_error_fail': False, 'verbose': False}
INFO     -  [macros] - Extra variables (config file): ['social', 'coda']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: …
```
=> Remove mkdocs-video plugin

CHANGELOG.md
`make release-manual` gets made if there are no release notes
=> Add release notes to make the release process happy

compiled_types.ts, dist/bundle.d.ts, dist/compiled_types.d.ts, requirements.txt
so we can check it when we consider if we want to show oauth as configurable for pack configurations
=> make endpoint key available in external metadata

Makefile
We've been running into problems where we build the SDK from a Mac arm machine, but then try to deploy that build to lambda in AWS which runs x86_64.
For now, this code assumes we always want x86_64.  We may run into Rosetta2 emulator issues when trying to run this on an arm64 dev machine, in which case we'll likely need to have two versions of this compilation step run, then be sure to select the correct one during test time vs. run time.  Will see how that lands and followup as necessary.
PTAL @coda/packs @dweitzman-codaio
=> [Node18] Ensure we build docker images for x86_64 architecture

docs/embedded-snippets/samples/snippets/formula/object_formula.html, docs/embedded-snippets/samples/snippets/sync_table.html, docs/samples/topic/data-type.md, docs/samples/topic/sync-table.md, documentation/generated/examples.json, documentation/generated/pack.code-snippets, documentation/generated/snippets.json, documentation/samples/snippets/formula/object_formula.ts, documentation/samples/snippets/sync_table.ts
The snippets that create a schema use the name `ThingSchema`, so this bring this inline. Also while having the sync table name and identity be one placeholder was convenient, I worry it will set a bad precedent, since the identity name should ideally be singular and the sync table name plural. Assigning to on-call.
=> Adjust snippets that use schemas

docs/guides/development/troubleshooting.md, docs/support/faq.md
Also deletes a section of the FAQ about icons which is obsolete with the introduction of custom icons.
=> Add information about HTTP debug logs

CHANGELOG.md, cli/coda.ts, cli/upload.ts, dist/cli/coda.js, dist/cli/upload.d.ts, dist/cli/upload.js, dist/helpers/external-api/v1.d.ts, helpers/external-api/v1.ts
For more context see https://github.com/coda/coda/pull/98327
=> Add --allowOlderSdkVersion param to `coda upload` to bypass upcoming constraint on SDK versions

CHANGELOG.md, dist/testing/upload_validation.js, testing/upload_validation.ts
According to my map reduce result, there's no sync tables in all envs that is using a `=` character in their identity name. And the `=` is not a valid character in coda object ids. So let's simply get rid of it. 
PTAL @patrick-codaio @dweitzman-codaio @alan-codaio 
cc @taj-codaio @chris-codaio
=> Stop supporting '=' in sync table identity names

docs/guides/advanced/schemas.md
With the new sync table storage there is no longer an issue with using a property named `id`. Assigning to on-call.
=> Remove tip about ID properties

docs/guides/basics/parameters/index.md
I created the Box sample Pack a while back to demonstrate this, but never linked to it from the docs. This PR adds a tip to the Parameters guide and links to the relevant code. Assigning to on-call.
=> Add information on obtaining the filename of a file parameter

Makefile, renovate.json5
Now that we're using the pipfile instead of requirements.txt to power renovate, it's running into trouble installing dependencies.
Example error: https://github.com/coda/packs-sdk/pull/2781#issuecomment-1771461730
Unfortunately I didn't document what the specific renovate error with _bootstrap-doc-tools was when I made https://github.com/coda/packs-sdk/pull/2646, I just linked to a PR exhibiting the error on which renovate has since deleted the comment with the actual error message
This may not work, but I'm having trouble testing renovate on branches other than the repo default branch, so it might be easiest to just merge a PR and see what happens
=> Try to fix renovate artifact building with pipenv

Makefile
It's not working as-is, so pipenv updates are still failing: https://github.com/coda/packs-sdk/pull/2776#issuecomment-1771635874
=> Try removing "sudo" from make _bootstrap-renovate

Makefile, renovate.json5
I tried to figure out how to install pillow & dev-jpeg in the container we have available, but it wasn't going well and I'm ready to surrender. Since we're not building the docs anyway, seems like it's probably fine to just skip installing the python dependencies during the post upgrade tasks
=> Give up on installing python-y things in postUpgradeTasks for renovate

renovate.json5
Looks like postUpgradeTasks is running successfully now, but requirements.txt isn't being added to PRs because it wasn't matching the file filters
I'm cautiously optimistic that after this PR, renovate for python will finally be sending out correct PRs
=> Include requirements.txt in postUpgradeTasks artifacts

dist/bundle.d.ts, dist/testing/auth.d.ts, dist/testing/auth.js, dist/testing/auth_types.d.ts, dist/testing/fetcher.d.ts, dist/testing/fetcher.js, dist/testing/oauth_helpers.d.ts, dist/testing/oauth_helpers.js, dist/testing/oauth_server.d.ts, dist/testing/oauth_server.js, dist/testing/upload_validation.js, dist/types.d.ts, docs/reference/sdk/interfaces/core.OAuth2Authentication.md, docs/reference/sdk/interfaces/core.OAuth2ClientCredentialsAuthentication.md, test/auth_test.ts, testing/auth.ts, testing/auth_types.ts, testing/fetcher.ts, testing/oauth_helpers.ts, testing/oauth_server.ts, testing/upload_validation.ts, types.ts
Adds functionality to request an access token and refresh it from the cli
Video showing execution of fedex pack, using the updated endpoint:
https://coda.d.pr/i/o7ulz7
PTAL @gary-codaio @jonathan-codaio
=> Add client credentials auth to coda CLI

CHANGELOG.md
Moving this doc back to unreleased based on https://github.com/coda/packs-sdk/pull/2801#discussion_r1370850312
PTAL @jonathan-codaio @dweitzman-codaio
=> Move extraOAuthScopes back to unreleased

package.json
This isn't really necessary and it causes warnings for people using higher node versions
=> Drop package.json constraint requesting node versions < 19

dist/runtime/bootstrap/index.d.ts, dist/runtime/bootstrap/index.js, runtime/bootstrap/index.ts
The goal here is to avoid the need to directly import isolated-vm in other repos, which avoids the need to manually upgrade isolated-vm in those repos
=> Export helpers for creating isolated-vm Isolate

docs/samples/topic/two-way.md, documentation/generated/examples.json, documentation/samples/packs/two-way/README.md
PR #2806 removes an outdated warning about two-way sync, but didn't make the change at the source. This PR extends that work and modifies the correct source file.
Assigning to on-call.
=> Finish PR 2806

renovate.json5, scripts/dev/install-pnpm.sh
This PR also re-enables pnpm upgrades, since pnpm is now a standalone install and won't conflict with other global node installations
=> Get the pnpm version from package.json

api.ts, dist/api.d.ts, dist/bundle.d.ts, docs/reference/sdk/interfaces/core.SyncFormulaDef.md
This may take longer to implement than anticipated, so it's probably best to hide in the docs until it's ready for use
=> Hide docs for updateOptions which make take some time to implement

CHANGELOG.md, package.json
- Added `OAuth2ClientCredentials` authentication type as a system authentication type.
=> packs-sdk: release v1.7.1

package.json
The usual reason
Last time we did this: https://github.com/coda/packs-sdk/pull/2704
=> Make a prerelease version number

dist/bundle.d.ts, dist/types.d.ts, docs/embedded-snippets/samples/packs/authentication/battlenet.html, docs/embedded-snippets/samples/snippets/authentication/system_oauth2_client_credentials.html, docs/embedded-snippets/samples/snippets/authentication/user_oauth2_client_credentials.html, docs/guides/basics/authentication/oauth2.md, docs/reference/sdk/interfaces/core.OAuth2Authentication.md, docs/reference/sdk/interfaces/core.OAuth2ClientCredentialsAuthentication.md, docs/samples/topic/apis.md, docs/samples/topic/authentication.md, documentation/generated/examples.json, documentation/generated/pack.code-snippets, documentation/generated/snippets.json, documentation/samples/packs/authentication/battlenet.ts, documentation/samples/snippets/authentication/system_oauth2_client_credentials.ts, documentation/samples/snippets/authentication/user_oauth2.ts, documentation/samples/snippets/authentication/user_oauth2_client_credentials.ts, documentation/scripts/documentation_config.ts, types.ts
- Updates OAuth2 guide to mention support for the Client Credentials flow, and disambiguate it with the Authorization Code flow.
- Adds a sample (Battle.net) for setting up client credentials authentication.
- Adds snippets for the quick setup of client credentials authentication.
=> Add docs for OAuth2 client credentials

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Apparently z.any() accepts undefined, so need to add additional validation to make sure that the example results are not falsy.
=> Validate the formula example results must be defined

CHANGELOG.md, api_types.ts, dist/api_types.d.ts, dist/bundle.d.ts, docs/reference/sdk/interfaces/core.FetchRequest.md
We don't allow caching non-`GET` requests by default, but some makers may want to cache the requests for non-side-effecting requests (for example, querying a GraphQL API). Adds the option to cache these results here when making those fetch calls.
=> Add option to cache non-GET requests in the `FetchRequest` interface

CHANGELOG.md, cli/coda.ts, cli/execute.ts, dist/cli/coda.js, dist/cli/execute.d.ts, dist/cli/execute.js, docs/guides/basics/authentication/index.md, docs/guides/basics/authentication/oauth2.md, docs/guides/basics/fetcher.md, docs/support/index.md
This change is based on feedback from Pack makers who became frustrated when they sunk a lot of time into developing a Pack only to realize at the end that it required Coda approval since it uses multiple domains.
=> Add warning when running a Pack with multiple domains

docs/guides/overview.md
Update the overview page to mention support for ES2022 language features, now that the Packs runtime has been updated to run on Node 18.
I tried updating `compile.ts` to target ES2022 directly, but ran into some errors. This is fine though, as esbuild will just downlevel any newer features.
=> Update documentation to mention compatibility with ES2022

dist/testing/execution.js, testing/execution.ts
There was a bug due to `Buffer.isBuffer()` not working if you created a non-native buffer in pack code and try to check if it's a buffer using native buffers in node_fetcher.ts
This forces non-native Buffers even for node_fetcher, ensuring consistent behavior
=> Fix buffer request bodies with `coda execute --vm=false`

docs/guides/blocks/sync-tables/two-way.md
Addressing feedback from @alexd-codaio:
> One minor nit (and may only be applicable to me and these weird dynamic tables) - the keyspaces of the `previousValue`, `newValue` and `updatedFields` is that of the "fromKey" (e.g. pretransformed state rather than the post-transformed state of the schema itself).
Updated the two-way sync guide to mention this behavior, and talk about tactics for transforming between API results and row schemas more generally.
=> Document two-way behavior with `fromKey`

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
There's a bug with autocomplete when multiple sync tables use the same formula name. It's probably possible to fix the autocomplete bug in isolation, but it seems reasonable to just disallow duplicate sync table formula names in the first place.
=> Require unique sync formula names

CHANGELOG.md, dist/testing/execution.d.ts, dist/testing/execution.js, test/execution_test.ts, test/packs/fake.ts, test/packs/fake_v2.ts, testing/execution.ts
Now supporting:
```bash
coda execute MyFormula:autocomplete:paramName [query] [formula context json]
coda execute MySync:autocomplete:paramName [query] [formula context json]
coda execute MySync:update [sync params] [sync update array json]
coda execute MyDynamicSync:getName
coda execute MyDynamicSync:getDisplayUrl
coda execute MyDynamicSync:getSchema
coda execute MyDynamicSync:listDynamicUrls [parentUrl]
coda execute MyDynamicSync:searchDynamicUrls [query]
coda execute Auth:getConnectionName
coda execute Auth:getConnectionUserId
coda execute Auth:postSetup:setEndpoint:stepName
```
Haven't considered PropertyOptions yet but think it could fit into this fairly naturally especially given it only works on top-level schema fields.
=> Add syntax for executing metadata formulas and sync updates from the CLI.

CHANGELOG.md, dist/testing/execution.js, dist/testing/helpers.d.ts, dist/testing/helpers.js, test/execution_test.ts, testing/execution.ts, testing/helpers.ts
The CLI `execute` command used `console.log` to output the results, with for objects routed to `console.inspect` to generate the output. That function by default collapses deep objects or long arrays, which isn't ideal when you are testing your Pack and want to see the full output.
This PR adds a new `printFull` helper function with for object output manually calls `console.inspect` with the collapsing turned off. `console.log` is used for other data types to preserve backwards compatibility.
=> Disable collapsing of `execute` output

dist/testing/execution.js, testing/execution.ts
The `search` argument of metadata functions should always be defined, but the new support in the `execute` function wasn't setting a default value when it wasn't specified on the command line.
=> Fix default value for `search` argument when executing metadata formulas

api.ts, bundles/thunk_bundle.js, dist/api.d.ts, dist/bundles/thunk_bundle.js, dist/runtime/thunk/thunk.js, runtime/thunk/thunk.ts
Normally we do implicit caching where the properties read during the propertyOptions formula are incorporated into the cache key. Some APIs can force packs to make an overly-specific request while getting more general information.
As a hypothetical example, imagine that some API requires you to pass in an email ID when fetching the all labels that your account can use, but the list of labels is actually the same for all emails. You might read `email_id` from the set of properties but then return it in the new `propertiesNotUsed` setting from this PR to prevent it from becoming part of the cache key
This feature is undocumented and not an officially-supported API, even at typescript level where it's not exposed to things like vscode autocomplete: for now it's only needed by advanced makers …
=> Advanced property options feature to ignore properties when caching

.circleci/config.yml
circleci is giving a warning about this: https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176
=> Remove hardcoded docker version from circleci

CHANGELOG.md, dist/testing/auth.js, dist/testing/oauth_server.d.ts, dist/testing/oauth_server.js, test/auth_test.ts, testing/auth.ts, testing/oauth_server.ts
Pack maker Troy recently raised the issue that endpoint URL features supported by OAuth2 authorization (`postSetup` and `endpointKey`) weren't be handled when auth'ing via the CLI. This PR does the following:
- Fully handles `endpointKey`
- Detects `postSetup` and prompts the developer to manually enter the endpoint URL.
Aside: I noticed while testing this feature that the CLI doesn't support PKCE, so swapped in a TODO for that.
=> Support endpoint for OAuth2 in the CLI

docs/guides/basics/fetcher.md, documentation/scripts/mkdocs_macros.py
Adding information about the User Agent header to the documentation. While there, also improved the information about IP addresses, to display the current set of IPs on the page directly (powered by a Python macro).
=> Add user agent and improve IP info

dist/bundle.d.ts, dist/schema.d.ts, dist/schema.js, package.json, schema.ts
* Add the domain principal type which will be required in certain packs-sync
* Proposal on adding a type to the user/groups principal types. This will allow us to do special handling for specific group and user types such as avoiding a user mapping table when the user type is email.
=> Add Domain Principal

cli/coda.ts, dist/cli/coda.js
The `coda build` command isn't required for normal usage, but this isn't clear today. This PR adjusts the help text to make this clearer. Snippet from the updated help text:
```
coda.ts build <manifestFile>              Build your Pack locally (not
required; for debugging purposes
only)
coda.ts upload <manifestFile>             Build and upload your Pack version
to Coda
```
=> Adjust help text for coda build

api_types.ts, dist/api_types.d.ts, dist/bundle.d.ts, dist/testing/upload_validation.js, package.json, test/upload_validation_test.ts, testing/upload_validation.ts
Discussion thread: https://github.com/coda/packs/pull/4161#discussion_r1645195276
For incremental sync, some parameters are not compatible with the sync token, for example `orderBy`, `q`, etc. in Google Calendar API:
Adding supportsIncrementalSync in ParamDef so that we can exclude params that does not support incremental sync in CSB
=> add supportsIncrementalSync in ParamDef to support incremental sync

api.ts, bundles/thunk_bundle.js, dist/api.d.ts, dist/api.js, dist/bundles/thunk_bundle.js, dist/runtime/common/marshaling/index.js, package.json, runtime/common/marshaling/index.ts
* add response too large error
* bump version to pre-release
=> Add ResponseTooLarge Error

docs/guides/advanced/images.md, docs/guides/basics/fetcher.md
Andrea pointed out that the old link 404's. Updated it to a new page.
=> Fix broken links to Buffer docs

dist/testing/upload_validation.js, package.json, test/upload_validation_test.ts, testing/upload_validation.ts
@chris-codaio @sam-codaio @jonathan-codaio PTAL
Missed this in the initial PR.
=> Fix schema validation to allow for arrays of strings when indexing properties

dist/bundle.d.ts, dist/schema.d.ts, dist/schema.js, package.json, schema.ts, test/execution_test.ts, test/packs/fake.ts
Part of the work for sibling ACLs. Updating permissions to have a new delegated type.
=> Update SDK to support sibling acls

api_types.ts, dist/api_types.d.ts, dist/bundle.d.ts, docs/reference/sdk/interfaces/core.TemporaryBlobStorage.md, package.json
@sam-codaio @neal-codaio PTAL
Already implemented on the `coda` side, just need to document.
=> Add contentType override for storeUrl

CHANGELOG.md, dist/handler_templates.js, dist/testing/execution.d.ts, dist/testing/execution.js, dist/testing/mocks.d.ts, dist/testing/mocks.js, docs/reference/sdk/interfaces/testing.MockExecutionContext.md, docs/reference/sdk/interfaces/testing.MockSyncExecutionContext.md, handler_templates.ts, test/compile_test.ts, test/execution_test.ts, test/handler_templates_test.ts, testing/execution.ts, testing/mocks.ts
<table><tr><td><details><summary>This PR is part of a stack created with <a href="https://github.com/aviator-co/av">Aviator</a>.</summary>
* **#3084**
* ➡️ **#3082**
* `main`
</details></td></tr></table>
Improving stubs in `MockExecutionContext` to be strongly typed.
Also adding a `transformSyncFormulaResultToGetPermissionsRequest` helper for writing tests working with permissions.
=> Improve types for mocking

dist/testing/upload_validation.js, test/upload_validation_test.ts, testing/upload_validation.ts
Without this, our current Google packs would break, and probably quite a few 3rd party ones.
=> Revert to allowing authorizationUrl & tokenUrl to not match networkDomain

dist/testing/fetcher.js, testing/fetcher.ts
Similar to https://github.com/coda/packs-sdk/pull/2528, this PR adds the `Host` header to the signature payload for `AWSAssumeRole` auth to fix a bug:
```
403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><HeadersNotSigned>host</HeadersNotSigned><RequestId>MP4AR6GAY20WJ36J</RequestId><HostId>yX2o3qvvxuDzmQ+Cka5cRkfQ1D7yv3eZMfjN4XGRTKkHrckEvysZCj9kZMcjY3a3s/vTyBFbcOo=</HostId></Error>"
```
=> Fix bug with AWSAssumeRole signing

CHANGELOG.md, package.json
Released: https://github.com/coda/packs-sdk/releases/tag/v1.8.2
=> packs-sdk: release v1.8.2

CHANGELOG.md, api_types.ts, dist/api_types.d.ts, dist/bundle.d.ts, dist/testing/fetcher.js, docs/reference/sdk/interfaces/core.TemporaryBlobStorage.md, docs/reference/sdk/interfaces/testing.MockExecutionContext.md, docs/reference/sdk/interfaces/testing.MockSyncExecutionContext.md, testing/fetcher.ts
I had wanted to cache some large blobs I was storing, so I didn't have to refetch them on every sync. This PR adjusts signature of `storeUrl` to support a `cacheTtlSecs` fetch option. The implementation already seems to support this (we likely pass through all of the options) but adjusting the typing to indicate it's supported.
I also fixed an issue with the testing fetcher where it wasn't using the fetch options.
=> Allow setting a cache time when storing URLs

dist/testing/upload_validation.js, package.json, test/upload_validation_test.ts, testing/upload_validation.ts
Noticed this while running some experimentation on dev that indexing strategies in pack schemas were being dropped. The strategy property is being ignored since `{property: 'blah', strategy: 'blah'}` still satisfies the property identifier schema without using `strict()`. Add strict so that schemas with `strategy` defined fall through to the `DetailedIndexedProperty` schema validation. Would've also worked by reordering the zod union.
=> Fix indexing strategy validation for object schemas

CHANGELOG.md, builder.ts, bundles/thunk_bundle.js, dist/builder.d.ts, dist/bundle.d.ts, dist/bundles/thunk_bundle.js, dist/runtime/thunk/thunk.js, dist/types.d.ts, package.json, runtime/thunk/thunk.ts, types.ts
Updating the thunk to properly invoke the correct authentication metadata formulas instead of always using the default.
PTAL @coda/packs / @alan-codaio
=> Handle getConnectionName, getConnectionUserId for admin authentications

dist/bundle.d.ts, dist/testing/upload_validation.js, dist/types.d.ts, docs/reference/sdk/interfaces/core.AWSAccessKeyAuthentication.md, docs/reference/sdk/interfaces/core.AWSAssumeRoleAuthentication.md, docs/reference/sdk/interfaces/core.BaseAuthentication.md, docs/reference/sdk/interfaces/core.CodaApiBearerTokenAuthentication.md, docs/reference/sdk/interfaces/core.CustomAuthentication.md, docs/reference/sdk/interfaces/core.CustomHeaderTokenAuthentication.md, docs/reference/sdk/interfaces/core.HeaderBearerTokenAuthentication.md, docs/reference/sdk/interfaces/core.MultiHeaderTokenAuthentication.md, docs/reference/sdk/interfaces/core.MultiQueryParamTokenAuthentication.md, docs/reference/sdk/interfaces/core.OAuth2Authentication.md, docs/reference/sdk/interfaces/core.OAuth2ClientCredentialsAuthentication.md, docs/reference/sdk/interfaces/core.QueryParamTokenAuthentication.md, docs/reference/sdk/interfaces/core.WebBasicAuthentication.md, package.json, test/upload_validation_test.ts, testing/upload_validation.ts, types.ts
As discussed in https://github.com/coda/coda/pull/120132#discussion_r1842933123, if a sync table uses meta-sync we want to _only_ use admin authentications, not the default authentication. So this PR moves `canSyncPermissions` into the authentications definition that lives in adminAuthentications.
=> CB-2904 Remove canSyncPermissions

dist/testing/upload_validation.js, package.json, test/upload_validation_test.ts, testing/upload_validation.ts
The premise here is that sync table identities can be duplicated if the allowedAuths are disjoint meaning that only 1 sync _table_ would be used in a certain context (brain, doc, etc) even if multiple identities exist.
Also fixes a validation bug where we throw an error if you try to use a `ReservedAuthenticationName` in the `allowedAuthenticationNames` field.
=> CB-2995 Allow identity names to be duplicated if allowedAuthenticationNames is disjoint

bundles/thunk_bundle.js, dist/bundles/thunk_bundle.js, dist/runtime/common/helpers.d.ts, dist/runtime/common/helpers.js, dist/runtime/thunk/thunk.js, dist/testing/execution.js, runtime/common/helpers.ts, runtime/thunk/thunk.ts, testing/execution.ts
Adds verification to our thunk so that we don't invoke formulas with connections created with unsupported authentication mechanisms. Will add unit tests
=> CB-2317 Verify authenticationName is supported when invoking Pack formulas

CHANGELOG.md, package.json
Released here: https://github.com/coda/packs-sdk/releases/tag/v1.8.5
=> packs-sdk: release v1.8.5

api_types.ts, dist/api_types.d.ts, dist/api_types.js, dist/bundle.d.ts, dist/index.d.ts, dist/runtime/bootstrap/index.d.ts, dist/runtime/bootstrap/index.js, dist/testing/execution.d.ts, dist/testing/execution.js, dist/testing/fetcher.js, dist/testing/ivm_helper.d.ts, dist/testing/ivm_helper.js, dist/testing/mocks.d.ts, dist/testing/mocks.js, docs/reference/sdk/functions/testing.executeFormulaOrSyncWithVM.md, docs/reference/sdk/interfaces/testing.MockSyncExecutionContext.md, index.ts, package.json, runtime/bootstrap/index.ts, testing/execution.ts, testing/fetcher.ts, testing/ivm_helper.ts, testing/mocks.ts
Discussion: https://coda.io/d/go-brainwriteups_dQYLHXsHZWS/Pack-SDK-Get-item-versions-interface_suFrdPVO?utm_source=slack#_luPjCMl1
Follow up: update `item ids` to `row ids` for ingestion related variables 
PTAL: @patrick-codaio @erickoledadevrel  @jonathan-codaio
=> Adding sync state service to get latest row version based on given row ids

package.json, pnpm-lock.yaml
Addresses https://github.com/coda/packs-sdk/security/dependabot/122
PTAL @neal-codaio @dweitzman-codaio @coda/packs
=> Bump path-to-regexp in SDK.

package.json, pnpm-lock.yaml
Addresses https://github.com/coda/packs-sdk/security/dependabot/74
There is no new version of `lodash.pick` to override to. But we're getting this transitively via `sharp-cli` so just update that. Sharp seemed to resolve this for themselves by downgrading lodash.pick to 3.x.
PTAL @neal-codaio @dweitzman-codaio @coda/packs
=> Upgrade sharp-cli to resolve lodash-pick vulnerability.

CHANGELOG.md, dist/testing/execution.d.ts, dist/testing/execution.js, test/execution_test.ts, testing/execution.ts
In https://github.com/coda/packs-sdk/pull/2895 the logic was changed to only show the error message if available, hiding the stack trace. This is desirable for errors originating from the CLI itself, but makes it harder to debug when the error comes from Pack code (see [community thread](https://community.coda.io/t/how-to-get-the-stack-trace-when-executing-using-the-coda-cli/53804)).
This PR wraps errors that are thrown from Pack code in a new custom error class, so that later those errors can be detected and the full stack trace printed. It also detects when the Node source maps feature is disabled and logs a warning.
```sh
❯ node dist/cli/coda.js execute test/packs/fake.ts Throw                                             
here
```
```sh
❯ node dist/cli/coda.js execute …
```
=> Show stack traces for errors thrown by Pack code

cli/execute.ts, dist/runtime/types.d.ts, dist/testing/execution.js, dist/testing/helpers.d.ts, dist/testing/helpers.js, runtime/thunk/thunk.ts, runtime/types.ts, test/execution_test.ts, test/packs/fake.ts, testing/execution.ts, testing/helpers.ts
This PR adds the ability to get rowAccessDefinitions for a sync table from the CLI.
Previously, we had the ability to explicitly fetch permissions for rows, but you had to give the rows in a json parameter. This mode of Sync will instead do the sync fetching, pipe those into GetPermissions, and then return the result.
Screencast: https://coda.d.pr/v/3H3gwW
=> Call executeGetPermissions with actual sync from cli

dist/runtime/types.d.ts, dist/testing/execution.js, dist/testing/types.d.ts, dist/testing/types.js, runtime/types.ts, test/execution_test.ts, test/packs/fake.ts, testing/execution.ts, testing/types.ts
This PR adds support for calling an incremental sync from the CLI.
When calling MyTable>incremental, we will:
- Parse the call into a Sync formula and then another Sync formula inside of a chained command object.
- Run the first sync until it hits a completion (without a concurrent continuation)
- Run the second sync using the completion from the first sync in the executionContext
- Return the results from the second (incremental) sync
Some notes:
- We do not run the confirmation loop in an arbitrary length, we're essentially just grabbing the second "batch" defined by confirmations
- We do not currently allow MyTable:incremental to be called directly, but can add support for this later.
- The internal logic for > syntax was updated to allow some commands to be run in the continuation …
=> Allow incremental sync from CLI

CHANGELOG.md, package.json
Releasing new version. Somehow got skipped to 1.9.5 😭 . New tag here
```https://github.com/coda/packs-sdk/releases/new?tag=v1.9.5&title=Release+1.9.5&body=-+Update+%60IndexDefinition%60+to+encompass+either+%60CustomIndexDefinition%60+or+%60CategorizedIndexDefinition%60.+%60CustomIndexDefinition%60+will+be+backwards+compatible+with+releases+from+before+1.9.4+and+refer+to+the+old+%60IndexDefinition%60.+The+%60CategorizedIndexDefinition%60+will+support+specific+types+of+indexable+content+that+has+been+predefined+in+the+sdk.%0A-+Add+a+new+%60filteredProperities%60+field+to+%60schema.index%60+to+specify+additional+columns+that+can+be+used+to+filter+down+query+results.%0A-+Minor+documentation+updates.%0A-+Deprecate+%60PrincipalType.Anyone%60.%0A-+Remove+%60popularityNormProperty%60+and+%60author …
```
=> Release 1.9.4

dist/testing/upload_validation.js, package.json, testing/upload_validation.ts
This is used in `validatePackVersionMetadata` which is used on pack upload to strip out extraneous fields. I do not want validateParameters to be stripped out
=> include validateParameters in zod commonPackFormulaSchema otherwise it gets stripped out on upload

CHANGELOG.md, dist/testing/fetcher.js, testing/fetcher.ts
Addresses https://staging.coda.io/d/_dEE5xhCKh9I#Bug-Triage_tu9rR8Oj/r7437
PTAL @ekoleda-codaio @coda/packs 
Feel free to merge this yourself, as I'll be OOO by the time this is reviewed.
=> Don't double-encode paths in AWSAccessKey auth.

package.json
Based on this Slack conversation:
https://grammarly.slack.com/archives/C01835XEBSS/p1752699589963099
This PR updates the packs-sdk semantic version in package.json to avoid a known issue with the Coda linter job.
We’ve previously observed that when the commit hash changes without a corresponding semantic version bump in the SDK, the Coda linter job can take over an hour to run. The root cause is still unknown, and the issue may still recur.
To mitigate this, we follow the practice of always updating the SDK version to a prerelease when bumping the SDK in Coda. This PR bumps the version to:
```
1.9.12-prerelease.1
```
This ensures that the Coda linter job runs as expected and avoids the performance degradation.
=> Bumped up version number (1.9.12-prerelease.1)

package.json
Following https://github.com/coda/packs-sdk/pull/3263, this PR bumps the semantic version so that we can pull the changes into the coda repo
=> Bump semantic version 1.9.13-prerelease.1

package.json, pnpm-lock.yaml
I noticed some packages that are old or deprecated.  It would be good to keep more of these up to date.  Probably drop some off where possible.  `release-it` and `@julian_cataldo/remark-lint-frontmatter-schema`
PTAL @jonathan-codaio @patrick-codaio @ekoleda-codaio
=> Upgrade packages to avoid security issues
