CHANGELOG.md
cli/init.ts
dist/cli/init.js
package.json

Fix coda init after module renames.

---

Makefile

Add Makefile command to publish to npm with proper tags.

---

dist/testing/fetcher.js
testing/fetcher.ts

I haven't tested this but it seems okay.

handle application/xml content type

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

PTAL @huayang-codaio @coda/packs

Fix validation RTE when using system authentication.

---

cli/errors.ts
dist/cli/errors.d.ts
dist/cli/errors.js

I copied the wrong error message 🤣😭

Fix the action message when running dev server with CLI

---

bundles/thunk_bundle.js
dist/bundles/thunk_bundle.js
dist/runtime/common/helpers.d.ts
dist/runtime/common/helpers.js
dist/runtime/thunk/thunk.d.ts
dist/runtime/thunk/thunk.js
dist/testing/execution.js
runtime/common/helpers.ts
runtime/thunk/thunk.ts
testing/execution.ts

@jonathan-codaio per https://github.com/coda/packs-sdk/pull/1241#discussion_r679272473

move unnecessary methods out of thunk

---

cli/create.ts
dist/cli/create.js

Just a sanity-check, because right now no matter what path you type, we'll be happy with it and stick your newly-created pack id in the directory.
PTAL @patrick-codaio @coda/packs

Check that the manifest file exists during coda create.

---

CHANGELOG.md
package.json

I don't seem to have this package in my npm account (huayang@coda.io). @jonathan-codaio can you help publish this?

create 0.4.5 release

---

dist/documentation/documentation_config.js
documentation/documentation_config.ts
documentation/generated/snippets.json
documentation/snippets/object_schema.ts

* adds the object schema snippet for autocomplete :)

add object schema snippets

---

.circleci/config.yml

Confirmed the config is syntactically valid using `circleci config validate`.

Don't attempt to build the gh-pages branch

---

docs/get-started/web.md

Noticed by @abhishek-codaio during Packademy.

Fix button location description

---

cli/coda.ts
cli/upload.ts
dist/cli/coda.js
dist/cli/upload.d.ts
dist/cli/upload.js

https://codaproject.slack.com/archives/C02ERJRBA21/p1632424836411200

add timerStrategy option to coda upload

---

cli/coda.ts
cli/create.ts
dist/cli/coda.js
dist/cli/create.d.ts
dist/cli/create.js

Just plumbing this in so users don't have to use their default WS to create Packs!

Allow users to specify workspaceId when creating a Pack via CLI

---

docs/get-started/cli.md
docs/get-started/web.md
mkdocs.yml

Remove references to the Packs adhoc.

Update docs for beta

---

package.json
yarn.lock

Addreses https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/Bugs_sucBW#Bugs_tuq-W/r19648&modal=true

Resolution for ansi-regex for security vulnerability.

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Working on making sure all of our v1 packs can pass our validation checks so they can be uploaded in the v2 flow. Had to add several more exemptions for bad sync tables, previously we were only handling bad identity names but there are also cases of sync tables whose getter formula names contain spaces. (These might be fixable, but I'm worried that they're in the sync automation rule so can't be fixed without an upgrade.)
PTAL @huayang-codaio @patrick-codaio @alan-codaio @coda/packs

Add more exemptions for bad legacy sync tables.

---

CHANGELOG.md
cli/coda.ts
development.ts
dist/cli/coda.js
dist/development.js
dist/testing/execution.d.ts
dist/testing/execution.js
testing/execution.ts

simple change. default CLI execute with vm option.

default CLI execute in vm

---

CHANGELOG.md

Update changelog to note that the CLI supports auto-versioning now.

---

docs/guides/advanced/libraries.md

Staged: https://coda-packs-sdk.readthedocs-hosted.com/en/ek-libraries/guides/advanced/libraries/

Add libraries guide

---

api_types.ts
dist/api_types.d.ts
dist/bundle.d.ts
docs/reference/sdk/enums/PrecannedDateRange.md
docs/reference/sdk/interfaces/ExecutionContext.md
docs/reference/sdk/interfaces/FetchRequest.md
docs/reference/sdk/interfaces/FetchResponse.md
docs/reference/sdk/interfaces/Fetcher.md
docs/reference/sdk/interfaces/SyncExecutionContext.md
docs/reference/sdk/interfaces/TemporaryBlobStorage.md

TSDoc for ExecutionContext and friends.

---

dist/testing/fetcher.d.ts
dist/testing/fetcher.js
package.json
testing/fetcher.ts
yarn.lock

PTAL @jonathan-codaio @huayang-codaio 
Confirmed this works with a dummy pack:
```
❯ ./node_modules/.bin/coda execute ./pack.ts MyFormula --fetch
[
{
name: 'browserless-chrome',
arn: 'arn:aws:ecr:us-west-2:560248293975:repository/browserless-chrome',
uri: '560248293975.dkr.ecr.us-west-2.amazonaws.com/browserless-chrome'
},
{
name: 'release',
arn: 'arn:aws:ecr:us-west-2:560248293975:repository/release',
uri: '560248293975.dkr.ecr.us-west-2.amazonaws.com/release'
},
{
name: 'integration-web',
arn: 'arn:aws:ecr:us-west-2:560248293975:repository/integration-web',
uri: '560248293975.dkr.ecr.us-west-2.amazonaws.com/integration-web'
},
{
name: 'icons-build',
arn: 'arn:aws:ecr:us-west-2:560248293975:repository/icons-build',
uri: '560248293975.dkr.ecr.us-west-2.amazonaws.com/icons-build'
},
{ …
```

Add AWSAccessKey simulator support

---

dist/testing/fetcher.d.ts
dist/testing/fetcher.js
package.json
testing/fetcher.ts
yarn.lock

Add simulator support for the newer AWS auth type - role assumption.
PTAL @jonathan-codaio @huayang-codaio

Add AWS role simulator support

---

test/upload_validation_test.ts

Due to stale dependabot branch.

Fix merge conflict.

---

test/typedoc_coverage_test.ts
typedoc.js

Treat TypeDoc warnings as errors so we enforce better coverage.

---

CHANGELOG.md
dist/testing/fetcher.js
package.json
testing/fetcher.ts

PTAL @huayang-codaio @spencer-codaio @coda/packs

SDK simulator: Better handling of XML headers for fetcher response parsing.

---

package.json
yarn.lock

Addresses https://github.com/coda/packs-sdk/security/dependabot/yarn.lock/json-schema/open
PTAL @alan-codaio @coda/packs

Add resolution for jsprim to address json-schema vulnerability.

---

CHANGELOG.md
cli/helpers.ts
cli/init.ts
dist/cli/helpers.js
dist/cli/init.js
dist/testing/ivm_helper.js
testing/ivm_helper.ts

PTAL @ekoleda-codaio @huayang-codaio @coda/packs

Fix path-related errors on Windows.

---

CHANGELOG.md
dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Addresses https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/My-Issues_sud-l#My-issues_tui9H/r20548&modal=true
PTAL @ekoleda-codaio @alan-codaio @coda/packs

Fix bugs in validation for examples with array parameters.

---

CHANGELOG.md
cli/coda.ts
dist/cli/coda.js

I think this should do the trick?
PTAL @ekoleda-codaio

Default the --fetch flag to false.

---

docs/reference/changes.md
mkdocs.yml

Staged: https://coda-packs-sdk--1654.com.readthedocs.build/en/1654/reference/changes/

Add changelog to docs

---

dist/bundle.d.ts
dist/testing/upload_validation.js
dist/types.d.ts
docs/reference/sdk/interfaces/OAuth2Authentication.md
testing/upload_validation.ts
types.ts

PTAL @huayang-codaio @ekoleda-codaio @coda/packs

Restrict the scope delimiter to only specific characters.

---

.circleci/config.yml
documentation/theme/main.html
mkdocs.yml

update new urls in packs-sdk and remove the noindex

take care of todos with new url

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Context: https://codaproject.slack.com/archives/CGLP9V98C/p1641251870120700

Do not allow giant pack versions

---

dist/documentation/documentation_publisher.js
documentation/documentation_publisher.ts

create cloudfront invalidation for the `.../latest` path on upload

invalidate the latest folder on clodfront on push

---

documentation/theme/main.html

will test by checking the upload to readdocs from the pr

add some meta tags

---

compiled_types.ts
dist/bundle.d.ts
dist/compiled_types.d.ts

Context: https://codaproject.slack.com/archives/CGLP9V98C/p1641424593139600

Add oauth fields that security-minded end users might want to see into ExternalPackVersionMetadata

---

dist/documentation/documentation_publisher.js
documentation/documentation_publisher.ts

remove the extraneous `packs` in the url when pushing
see https://github.com/coda/infra/pull/2337
@coda/packs

remove extraneous "packs" in url

---

docs/guides/best-practices.md
docs/guides/blocks/column-formats.md

Last round of best practices (for now).

Even more best practices

---

README.md
scripts/update-docs.sh

add temp script while CI is broken for the relase flow due to the security issue and update some docs 
cc @ekoleda-codaio @coda/packs @jonathan-codaio

add script + update readme

---

package.json
yarn.lock

Addresses https://github.com/coda/packs-sdk/security/dependabot/yarn.lock/marked/open

Add resolution for marked to address vulnerability.

---

.github/dependabot.yml

Change dependabot to monthly. Change reviewing team to coda/packs.

---

docs/guides/development/cli.md

Based on a dev question about passing dates.

Add examples for CLI params

---

docs/guides/best-practices.md

Link to the new guides for launching and promoting your Pack.

Add links to other best practices

---

docs/guides/advanced/dates.md
docs/guides/basics/parameters/index.md

Staged: https://coda-packs-sdk--1748.com.readthedocs.build/en/1748/guides/basics/parameters/#types

Add information about parameter types

---

package.json
yarn.lock

Resolution for nanoid vulnerability.

---

dist/testing/fetcher.js
testing/fetcher.ts

remove sanitization of the body for custom auth type as per https://github.com/coda/coda/pull/66987/

update fetcher sanitization to match coda

---

CHANGELOG.md
package.json

changelog for #1789 
i dont think we've published this version as huayang updated this not too long ago but lmk if we have
@jonathan-codaio

add packs-sdk 0.8.2 for StringEmbedSchema

---

docs/guides/basics/data-types.md
docs/guides/basics/parameters/index.md

Add mappings for Link, Canvas, and Email column types.

Add mappings for new column types

---

CHANGELOG.md
README.md
package.json

consolidating the 0.8.2 updates and updating readme with new CHANGELOG practices as discussed in slack

consolidate 0.8.2 updates

---

docs/guides/advanced/fetcher.md
docs/support.md

[Staged](https://coda-packs-sdk--1830.com.readthedocs.build/en/1830/support/#network-domains)

Add link to network domain request form

---

cli/coda.ts
dist/cli/coda.js

Actually default --fetch to true.

---

Makefile
docs/guides/basics/data-types.md
docs/guides/blocks/sync-tables/index.md
docs/support.md
docs/tutorials/get-started/web.md
package.json
yarn.lock

Pack maker Louca found an undefined reference in the sync tables guide. Fixed it, and added a lint check which caught a few others.

Add lint for missing references

---

dist/documentation/documentation_publisher.js
documentation/documentation_publisher.ts

missing a * here to invalidate the whole path

on docs push  invalidate whole path

---

docs/guides/development/cli.md
docs/tutorials/get-started/cli.md

Also includes a few minor tweaks to the CLI quickstart.

Update guides for coda clone and link.

---

.github/actions/release.yml
.release-it.json
CHANGELOG.md
Makefile
README.md
package.json
yarn.lock

something got busted with #1827 where it was generating a bunch of weird diffs on `make build` so im migrating to a new branch
@coda/packs @jonathan-codaio @huayang-codaio

auto release via release-it

---

CHANGELOG.md
package.json

commit made by `release-it` for releasing 0.9.0

packs-sdk: release v0.9.0

---

package.json
yarn.lock

Addresses https://github.com/coda/packs-sdk/security/dependabot/10
PTAL @huayang-codaio @coda/packs

Add resolution for minimist to address vulnerability.

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

My own fallibility around this is why I was hoping to be able to take advantage of Zod to generate the paths 😄 

Fix error path generation for deprecation warnings.

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

I think this covers the rest of the breaking changes described in the changelog that can be validated statically in this way.
@patrick-codaio I had wanted to validate that dynamic sync table are specifying an `identityName`, but because we validate the post-compiled metadata, and the code applies the sync table's name as a fallback identity name right now, we can't distinguish the cases and so can't flag anything for the maker here. Ideally we could tell a maker all the breaking changes they will face in the future, but I don't see how here. I think what we'll want to remember to do, is when we eliminate the fallback and require identityName, we should do so with a clear error message that tells people to add `identityName` and to set it to the value of `name` to avoid breaking an …

Validate more deprecated fields.

---

CHANGELOG.md

Figured the changelog should include mention of this for completeness.

Mention the new deprecation warnings stuff in the changelog.

---

CHANGELOG.md

@jonathan-codaio @coda/packs PTAL

Fix CHANGELOG since the transformBody change did not make it into 0.11

---

CHANGELOG.md

Also marked the ungzip behavior as a breaking change, not a future breaking change

Sort breaking changes above future breaking changes

---

docs/guides/advanced/authentication.md
docs/guides/advanced/fetcher.md
docs/support/migration/v0.11.0.md

Clarify that this new requirement only applies to user authentication.

Clarify networkDomain auth change

---

.github/workflows/combine.yml

Batch all green dependabot PRs into one 
Followed info [here](https://github.com/coda/coda/pull/70788) to add deploy key and ssh key 
`ssh-keygen -t ed25519 -C "git@github.com:coda/packs-sdk.git"`

batch dependabot

---

CHANGELOG.md
development.ts
dist/development.d.ts
dist/development.js
dist/testing/execution.d.ts
dist/testing/execution.js
testing/execution.ts

A partner suggested this, seems reasonable to keep expanding our test capabilities: https://codaproject.slack.com/archives/C01R3HSGMCJ/p1651787065542659?thread_ts=1651782749.991309&cid=C01R3HSGMCJ
PTAL @huayang-codaio @ekoleda-codaio @coda/packs

Add newRealFetcherExecutionContext test helper wrapper for users who want to test helper functions directly.

---

docs/guides/development/pack-maker-tools.md

update docs to mention you must be on latest release to publish or templatize

---

docs/guides/blocks/sync-tables/index.md

I've noticed a few developers being confused by the continuation flow, tried adding a diagram to clear it up. The layout isn't 100% perfect, but Mermaid doesn't provide much control there.
Staged here: https://coda-packs-sdk--1993.com.readthedocs.build/en/1993/guides/blocks/sync-tables/#longrunning

Add digram for continuations

---

CHANGELOG.md

after this merges i can tag the latest commit on main as v0.12.0 and then add release on npm + github

update changelog for 0.12.0 release

---

cli/init.ts
dist/cli/init.js

Escape shell characters in coda init.

---

docs/guides/development/cli.md

Fix coda init to npx coda init in guide.

---

dist/bundle.d.ts
dist/schema.d.ts
docs/reference/sdk/enums/AttributionNodeType.md
docs/reference/sdk/functions/generateSchema.md
docs/reference/sdk/functions/makeAttributionNode.md
docs/reference/sdk/functions/makeObjectSchema.md
docs/reference/sdk/functions/makeReferenceSchemaFromObjectSchema.md
docs/reference/sdk/functions/makeSchema.md
docs/reference/sdk/interfaces/ImageAttributionNode.md
docs/reference/sdk/interfaces/LinkAttributionNode.md
docs/reference/sdk/interfaces/ObjectSchemaDefinition.md
docs/reference/sdk/interfaces/TextAttributionNode.md
docs/reference/sdk/types/AttributionNode.md
docs/reference/sdk/types/InferrableTypes.md
docs/reference/sdk/types/Schema.md
docs/reference/sdk/types/SchemaType.md
schema.ts

Same as https://github.com/coda/packs-sdk/pull/2014 but with a build.
PTAL @ekoleda-codaio

Update documentation for featuredProperties.

---

CHANGELOG.md

Making a new minor release so the `CodaApiHeaderBearerToken` changes are available to 3rd party pack makers

Update changelog for 0.12.1 release

---

docs/support/index.md

While I was there I changed some of the formatting around, and simplified the community buttons.

Add office hours to support page

---

dist/testing/auth.js
testing/auth.ts

PTAL @ekoleda-codaio @coda/packs 
Addresses https://staging.coda.io/d/_d-GJF-DmEUK#Bugs_tuq-W/r22181&view=modal

Prompt for endpoint url with AWS auth types in CLI.

---

CHANGELOG.md
cli/init.ts
dist/cli/init.js

Addresses https://staging.coda.io/d/_d-GJF-DmEUK#Bugs_tuq-W/r22691&view=modal
PTAL @alan-codaio @ekoleda-codaio @paulwilkins-codaio

Fix coda init to install the SDK if it's not already.

---

docs/guides/index.md

Made this an index page in #2048 and forgot to adjust the relative image URLs accordingly.

Fix image URLs

---

CHANGELOG.md
package.json

packs-sdk: release v1.0.0

---

docs/guides/basics/parameters/autocomplete.md

update dynamic autocomplete snippet comment (typo)

---

dist/testing/fetcher.js
dist/testing/node_fetcher.d.ts
dist/testing/node_fetcher.js
testing/fetcher.ts
testing/node_fetcher.ts

This will match production behavior.

Sync up test fetcher with body Buffer fix

---

CHANGELOG.md
dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Report "example.com/path" as an invalid network domain

---

dist/cli/helpers.d.ts
dist/testing/helpers.d.ts
package.json
yarn.lock

See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/

Update typescript to 4.7; update eslint

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Context: https://github.com/coda/packs-sdk/pull/2043/files#r900703433

Make identityName optional for pre-1.0 packs

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Fix for https://coda-final.oslash.com/o/bug/23804

Prevent pack makers from using reserved column names

---

docs/embedded-snippets/examples/apis/yahoo.html
docs/samples/topic/apis.md
documentation/examples/apis/yahoo.ts
documentation/generated/examples.json
documentation/scripts/documentation_config.ts

To help a developer on Twitter: https://twitter.com/DustinRGood/status/1541852934215847936

Add Yahoo sample

---

dist/testing/compile.js
testing/compile.ts

o/bug/24021
Tested by temporarily modifying the code to error on Darwin kernels lower than 22, which works for me since I'm on macOS Monterey.
Example output:
```
$ ./node_modules/.bin/ts-node ./cli/coda.ts build index.ts
coda.ts build <manifestFile>
Generate a bundle for your Pack
Options:
--version                      Show version number               [boolean]
--help                         Show help                         [boolean]
-o, --outputDir                                                       [string]
--minify                                         [boolean] [default: true]
--timerStrategy                Options: none, error, fake.
[string] [default: "none"]
--intermediateOutputDirectory                                     [string]
Error: Packs SDK requires OS X version …
```

Improve error on unsupported OS X version (<10.13.0)

---

CHANGELOG.md
package.json

release v1.0.2

---

CHANGELOG.md
Makefile

Failed run: https://app.circleci.com/pipelines/github/coda/packs-sdk/6767/workflows/2cf7cdb2-c57f-4e52-afca-ff0b6d993f99/jobs/7465

Lint for unreleased name in changelog

---

CHANGELOG.md
package.json

https://www.npmjs.com/package/@codahq/packs-sdk/v/1.0.4
PTAL @spencer-codaio @coda/packs

packs-sdk: release v1.0.4

---

CHANGELOG.md
package.json

1.0.5 is released. @coda/packs

packs-sdk: release v1.0.5

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

See https://github.com/coda/coda/pull/76849

more details in the validation error message

---

docs/guides/development/testing.md

The assert one seems required at the very last.

Add chai and mocha imports to testing code snippets

---

.gitignore
docs/guides/basics/data-types.md
docs/samples/topic/column-format.md
documentation/examples/column-format/README.md
documentation/generated/examples.json

Fixing more typos reported by Bill French.

Fix more typos

---

docs/reference/sdk/interfaces/core.OptionalParamDef.md
docs/reference/sdk/types/core.ParamDefFromOptionsUnion.md

Merge conflict.

---

docs/tutorials/get-started/web.md

[Preview](https://coda-packs-sdk--2281.com.readthedocs.build/en/2281/tutorials/get-started/web/)

Add video walkthrough for the Pack Studio getting started tutorial

---

api.ts
bundles/thunk_bundle.js
dist/bundles/thunk_bundle.js
dist/runtime/bootstrap/index.d.ts
dist/runtime/bootstrap/index.js
dist/runtime/thunk/thunk.d.ts
dist/runtime/thunk/thunk.js
dist/runtime/types.d.ts
dist/runtime/types.js
dist/testing/execution.js
runtime/bootstrap/index.ts
runtime/thunk/thunk.ts
runtime/types.ts
testing/execution.ts

PTAL @jonathan-codaio @huayang-codaio 
CC @coda/packs

[TwoWaySync] Execution / thunk path changes

---

dist/runtime/common/marshaling/index.d.ts
dist/runtime/common/marshaling/index.js
runtime/common/marshaling/index.ts

to be used in https://github.com/coda/coda/pull/80588
PTAL @dweitzman-codaio @chris-codaio

expose isMarshaledValue

---

docs/assets/custom.css
documentation/theme/main.html
mkdocs.yml

[Preview](https://coda-packs-sdk--2294.com.readthedocs.build/en/2294/)

Add webinar banner

---

docs/tutorials/.nav.yml
docs/tutorials/index.md

Promote tutorials created by the community (currently just the one). [Preview](https://coda-packs-sdk--2295.com.readthedocs.build/en/2295/tutorials/).

Add community tutorials

---

CHANGELOG.md
api_types.ts
bundles/thunk_bundle.js
dist/api_types.d.ts
dist/bundle.d.ts
dist/bundles/thunk_bundle.js
dist/runtime/thunk/thunk.js
dist/testing/fetcher.js
dist/testing/node_fetcher.d.ts
dist/testing/node_fetcher.js
docs/reference/sdk/interfaces/core.FetchRequest.md
runtime/thunk/thunk.ts
test/auth_test.ts
testing/fetcher.ts
testing/node_fetcher.ts

PTAL @huayang-codaio @ekoleda-codaio @packs

Add a bit to fetcher requests for ignoreRedirects.

---

CHANGELOG.md
package.json
yarn.lock

packs-sdk: release v1.2.1

---

CHANGELOG.md
package.json

packs-sdk: release v1.2.2

---

dist/testing/upload_validation.js
testing/upload_validation.ts

See https://github.com/coda/packs-sdk/pull/2349/files#r1036262881

Fix credentailsLocation validation

---

docs/tutorials/get-started/cli.md

Mostly wanted to say that the guide is very intuitive to follow, nice work!

Just a missing word and updated error message

---

CHANGELOG.md
package.json

packs-sdk: release v1.2.3

---

renovate.json5

PTAL @coda/packs @jonathan-codaio

Fix silly typo renovate config

---

.prettierrc
.prettierrc.js

Coda is updating our repos to use a new prettier config file format. If you use the Prettier plugin in VSCode, you'll need to update your settings:

Migrate prettier config file

---

dist/handler_templates.d.ts
dist/handler_templates.js
handler_templates.ts
test/handler_templates_test.ts

Needed for mapping arrays of object keys from Coda->Pack.

Add utility to unmap keys

---

CHANGELOG.md

Adds a note capturing the change in #2350.

Add Node 19 fix to the changelog.

---

docs/guides/.nav.yml
docs/guides/design.md
documentation/samples/packs/todoist/simple.ts

[Preview](https://coda-packs-sdk--2470.com.readthedocs.build/en/2470/guides/design/)

Add design guide

---

.release-it.json
CHANGELOG.md
package.json

Disable error when current version has no changelog entry

packs-sdk: release v1.3.0

---

package.json
pnpm-lock.yaml

This PR was written using `pnpm audit --fix`

Disallow insecure xml2js and vm2

---

CHANGELOG.md
package.json

PTAL @patrick-codaio @gary-codaio / cc @coda/packs 
Patch release to get 'placeholder' property in PropertyIdentifierDetails

packs-sdk: release v1.3.3

---

CHANGELOG.md

Oops apparently releasing requires a changelog entry, so adding one.
PTAL @gary-codaio @patrick-codaio

Update changelog for placeholder

---

CHANGELOG.md
package.json

Release SDK for placeholder bug fix
PTAL @patrick-codaio @gary-codaio

packs-sdk: release v1.3.4

---

docs/guides/basics/data-types.md

Fixes [bug-32471](https://staging.coda.io/d/New-QT_dEE5xhCKh9I/My-Bugs_suswO#Assigned-to-Me_tu8Eu/r2471&modal=true).

Fix duration docs

---

package.json

Bump version to enable syncing into primary repo

---

dist/bundle.d.ts
dist/types.d.ts
dist/types.js
docs/guides/basics/authentication/index.md
docs/guides/basics/authentication/oauth2.md
docs/guides/basics/fetcher.md
docs/reference/sdk/enums/core.AuthenticationType.md
docs/reference/sdk/interfaces/core.CustomAuthentication.md
docs/support/index.md
types.ts

[Preview](https://coda-packs-sdk--2606.com.readthedocs.build/en/2606/guides/basics/authentication/#custom-tokens)

Add approval notice for custom authentication

---

docs/guides/blocks/sync-tables/two-way.md
docs/samples/topic/two-way.md
documentation/generated/examples.json
documentation/samples/packs/two-way/README.md

Also a small fix to some sample code I found.

Rebrand the 2way beta as an alpha

---

package.json
pnpm-lock.yaml

Addresses https://nvd.nist.gov/vuln/detail/CVE-2023-34104

Bump fast-xml-parser from 4.1.2 to 4.2.4

---

docs/guides/advanced/caching.md
docs/guides/basics/fetcher.md

- Document request de-duplication.
- Document a solution for `multipart/form-data`.

Misc docs additions

---

package.json

Same reason as https://github.com/coda/packs-sdk/pull/2467 -- somehow this impacts lint performance

Bump SDK version 1.4.0 to 1.4.1

---

docs/guides/blocks/sync-tables/two-way.md
docs/samples/topic/two-way.md
documentation/generated/examples.json
documentation/samples/packs/two-way/README.md

Allow people to request access to the two-way sync alpha.

Update alpha warning message

---

api.ts
dist/api.d.ts
dist/api.js
dist/bundle.d.ts
docs/reference/sdk/functions/core.makeSyncTable.md

Andrea discovered this while looking through an SEO report on our site.

Fix broken link in reference docs

---

docs/guides/advanced/schemas.md
docs/guides/basics/data-types.md
docs/guides/blocks/sync-tables/two-way.md

Update the documentation with more information related to two-way sync. This includes:
- Column IDs (`fixedId`)
- `SelectList` hint
- `allowNewValues`

Two-way sync updates

---

CHANGELOG.md

I meant to do this in https://github.com/coda/packs-sdk/pull/2797 but realize that my `git push` had failed and this didn't make it into the original PR

Update changelog for updateOptions

---

CHANGELOG.md
package.json

packs-sdk: release v1.7.0

---

docs/guides/blocks/cards.md

Clarify that card subtitles fallback to featured properties

---

docs/guides/blocks/sync-tables/two-way.md
docs/tutorials/videos.md

Add two-way sync webinar recording to the docs

---

dist/runtime/bootstrap/index.d.ts
dist/runtime/bootstrap/index.js
runtime/bootstrap/index.ts

Haven't tested yet, but seems like it should work

Fix the CLI commands depending on isolated-vm in a non-optional way

---

docs/guides/basics/fetcher.md

Addressing feedback from a [recent thread on the community](https://community.coda.io/t/disappearing-header-issue/44688).
Assigning to on-call.

Add warning about mixed credentials

---

dist/testing/upload_validation.js
package.json
test/upload_validation_test.ts
testing/upload_validation.ts

* Create Prerelease tag for users Role
* Add additional testing in upload_validation_test
* Fix logic in upload validation on property type

Add Prerelease tag for Users Role

---

dist/testing/upload_validation.js
test/upload_validation_test.ts
testing/upload_validation.ts

Address [this comment](https://github.com/coda/coda/pull/111352#discussion_r1623040110).

Verify scopes are non-empty for Google service accounts + DWD

---

CHANGELOG.md
package.json

Trying to address https://github.com/coda/packs/pull/4172#discussion_r1653466443
PTAL @neal-codaio @sam-codaio

Release new version to pick up popularity property change

---

dist/testing/upload_validation.js
package.json
testing/upload_validation.ts

Fixing for triggering version error due to default values
thread: https://codaproject.slack.com/archives/C02ERJRBA21/p1721857075068479
PTAL @chris-codaio @coda/packs

Remove default value for supportsIncrementalSync

---

CHANGELOG.md
package.json

See https://github.com/coda/packs-sdk/releases/tag/v1.7.12.

Release 1.7.12

---

dist/bundle.d.ts
dist/schema.d.ts
package.json
schema.ts

PTAL @patrick-codaio @sam-codaio @drew-codaio @coda/packs 
CC @ekoleda-codaio 
Eric we had a little meeting to discuss how to shape this, and how this overlaps with the concept of Identities, which I tried to capture in the comments.

Define a new ItemReference interface to use with DelegatedPermission.

---

CHANGELOG.md
api.ts
api_types.ts
dist/api.d.ts
dist/api_types.d.ts
dist/bundle.d.ts
package.json

* Add item in execute that allows for immediate re-triggering of a full sync

Add ability to trigger a full sync

---

CHANGELOG.md
api_types.ts
dist/api_types.d.ts
dist/bundle.d.ts
docs/reference/sdk/interfaces/core.TemporaryBlobStorage.md

context: https://github.com/coda/packs/pull/4336#discussion_r1739939836
ptal @oleg-codaio / @coda/packs

update storeUrl to also accept headers in fetchOpts

---

api_types.ts
dist/api_types.d.ts
dist/bundle.d.ts
package.json

Context: https://codaproject.slack.com/archives/C06QGU1AAN9/p1725903732419229

RFC: executionId

---

CHANGELOG.md
package.json

https://github.com/coda/packs-sdk/releases/tag/v1.7.16

packs-sdk: release v1.7.16

---

CHANGELOG.md
package.json

https://github.com/coda/packs-sdk/releases/tag/v1.7.17

Packs-sdk: release v1.7.17

---

docs/guides/basics/authentication/index.md

ran into these gotchas when trying to add a new pack with post setup, let me know if there's other places to make note

update docs for post setup

---

CHANGELOG.md
development.ts
dist/development.d.ts
dist/development.js
dist/testing/execution.d.ts
dist/testing/execution.js
package.json
testing/execution.ts

* Create equivalent test functions for new sync table methods

Test functions for executeUpdate and executeGetPermissions

---

CHANGELOG.md
package.json

https://github.com/coda/packs-sdk/releases/tag/v1.8.1

packs-sdk: release v1.8.1

---

CHANGELOG.md
package.json

packs-sdk: release v1.8.4

---

bundles/thunk_bundle.js
dist/bundles/thunk_bundle.js
dist/runtime/thunk/thunk.js
runtime/thunk/thunk.ts

I missed this spot although it's interesting we never checked this in the old code?

Fix thunk not being able to find system auth

---

package.json

For https://github.com/coda/packs-sdk/pull/3119

Bump pre-release version

---

api_types.ts
dist/api_types.d.ts
dist/bundle.d.ts
package.json

Make syncStateService optional to be compatible with UI sdk version

---

.eslintrc.js
cli/extensions.ts
cli/link.ts
dist/testing/compile.js
documentation/scripts/readthedocs_preprocess.ts
test/auth_test.ts
test/compile_test.ts
test/packs/fake_with_vm.ts
testing/compile.ts
testing/helpers.ts

Context: https://codaproject.slack.com/archives/C01835XEBSS/p1733862253044739

Disable the Browserify polyfill for vm

---

testing/ivm_helper.ts

Fix lint error

---

Makefile
runtime/native/node22/x86_64/isolated-vm/isolated-vm.js
runtime/native/node22/x86_64/isolated-vm/package.json

Node18 reaches end of life in April
Tested on lambda's node22 runtime, seems to work

Compile isolated vm on node22 also

---

dist/testing/oauth_server.js
package.json
pnpm-lock.yaml
testing/oauth_server.ts

PTAL @jonathan-codaio @patrick-codaio @dweitzman-codaio @ekoleda-codaio

Fix security warnings in cross-spawn and clear out unnecessary overrides

---

dist/testing/upload_validation.js
testing/upload_validation.ts

Follow-up to #3150
Doesn't seem useful here.

Don't eval json path

---

package.json

Bump prerelease version so we can bump the SDK in coda.

---

CHANGELOG.md
Makefile
package.json

Release v1.9.1

---

package.json

@jonathan-codaio @patrick-codaio PTAL
https://codaproject.slack.com/archives/C06QGU1AAN9/p1740163662988019

Bump version to 1.9.2-prerelease.1

---

package.json

Bumping up the SDK version to 1.9.2-prerelease.2

Bump up pre-release to 1.9.2-prerelease.2

---

CHANGELOG.md
package.json

For release packs using `GoogleDwdError`
PTAL @sam-codaio @coda/brain-platform

Bump the package version 

---

package.json
pnpm-lock.yaml

Addresses https://github.com/coda/packs-sdk/security/dependabot/144
PTAL @gary-codaio @coda/packs

Bump tar-fs to resolve vulnerability.

---

package.json
pnpm-lock.yaml

Addresses https://github.com/coda/packs-sdk/security/dependabot/141
PTAL @gary-codaio @coda/packs

Bump jsonpath-plus.

---

.circleci/config.yml

PTAL @alexd-codaio @neal-codaio @jonathan-codaio

Remove AWS user creds from CircleCI

---

dist/bundle.d.ts
dist/schema.d.ts
dist/schema.js
package.json
schema.ts

Details are in the comments of this Jira [ticket](https://grammarly.atlassian.net/browse/BL-77)

Remove @deprecate from PrincipalType.Anyone

---

docs/guides/basics/fetcher.md
docs/tutorials/videos.md

- Adding information about timeouts and retries for the fetcher.
- Adding a video to the videos page.

Minor doc updates

---

api_types.ts
dist/api_types.d.ts
dist/bundle.d.ts
dist/testing/upload_validation.js
docs/reference/sdk/interfaces/core.BaseFormulaDef.md
docs/reference/sdk/interfaces/core.CommonPackFormulaDef.md
docs/reference/sdk/interfaces/core.EmptyFormulaDef.md
docs/reference/sdk/interfaces/core.ObjectArrayFormulaDef.md
docs/reference/sdk/interfaces/core.PackFormulaDef.md
package.json
test/upload_validation_test.ts
testing/upload_validation.ts

initially had hoped to support this in all formulas but coda support needs more refinement so will start with only sync tables

upload validation only sync tables can have validateParameters

---

dist/bundle.d.ts
dist/schema.d.ts
dist/testing/upload_validation.js
schema.ts
test/upload_validation_test.ts
testing/upload_validation.ts

* Add arbitrary string support
* Remove arbitrary select list support

Change support for filterable properties

---

package.json
pnpm-lock.yaml

Addresses https://github.com/coda/packs-sdk/security/dependabot/145
PTAL @dweitzman-codaio @coda/orchestra-platform

Resolve vulnerability in tar-fs.

---

CHANGELOG.md
package.json

https://github.com/coda/packs-sdk/releases/tag/v1.9.9

packs-sdk: release v1.9.9

---

CHANGELOG.md
package.json

https://github.com/coda/packs-sdk/releases/tag/v1.9.10

packs-sdk: release v1.9.10

---

package.json
pnpm-lock.yaml

https://github.com/coda/packs-sdk/pull/3254 must have had a bad rebase and it undid a bunch of stuff I added for lint enforcement
PTAL @sam-codaio @coda/orchestra-platform

Fix package.json broken by https://github.com/coda/packs-sdk/pull/3254

---

CHANGELOG.md
package.json

https://github.com/coda/packs-sdk/releases/tag/v1.9.11

packs-sdk: release v1.9.11

---

CHANGELOG.md
package.json

packs-sdk: release v1.9.12

---

CHANGELOG.md
package.json
pnpm-lock.yaml

PTAL @coda/go-platform @ebo-codaio

Release version 1.11.0

---

dist/bundle.d.ts
dist/types.d.ts
types.ts

Add LLM facing description fields for pack formulas and skills. 
Full discussion: https://grammarly.slack.com/archives/C090L3BSAA1/p1759444251490569?thread_ts=1758746247.248289&cid=C090L3BSAA1

[Packs SDK] LLM-Facing Descriptions
